### PR TITLE
Towards 0.2

### LINKED ISSUE #67: sync standalone example with the example_ros_client one
The standalone example is far behind from the ros one. Rewrite so that they can be in sync with minimal effort.

### LINKED ISSUE #113: [QSRs] Deprecate and remove `include_missing_data`
What is the story with `include_missing_data`. Is it working and is it still needed or does it add an additional layer of possibly unneeded complexity?

### LINKED ISSUE #114: [QSRs] Also allow passing of `qsrs_for` in the `dynamic_args` within QSR namespace
Allow to pass `qsrs_for` in the QSR namespace of `dynamic_args`. Still allow `qsrs_for` to be passed in `kwargs` but `dynamic_args` namespace takes precedence.

Waits for #107 
Required as part of #112 
This issue blocks #111

### LINKED ISSUE #118: [QSRs] Make monadic and dyadic QSR abstract classes
Having monadic and dyadic QSR abstract classes saves a lot code repetition, e.g. [`def custom_checks_for_qsrs_for`](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/src/qsrlib_qsrs/qsr_rcc2_rectangle_bounding_boxes_2d.py#L42) is the same implementation for all dyadic.

**Reminder:** Use one file called `qsr_arity_abstractclass.py`; classes inherit from `QSR_Abstractclass`.

### LINKED ISSUE #119: [QSRlib_Request_Message] is a complete mess
As title says it is a mess. Both class methods `make` and `set_input_data` need to be cleaned up.

### LINKED ISSUE #122: [qsrlib_io] World_QSR_Trace.get_sorted_timestamps method does not look right
`World_QSR_Trace.get_sorted_timestamps` method does not look right.

### LINKED ISSUE #126: [qsr_lib] Remove every function call that is currently considered deprecated

### LINKED ISSUE #127: [qsr_lib] Switch from string output to dictionary output
This allows to natively support the multiple requests in one service call without having to specify the `future` option.

### LINKED ISSUE #134: [qsr_lib] Suggestion: Lose the 'make' function
This is a follow up of #133. Currently the `make` function is where all the magic happens but it also hosts a lot of duplicate code. Hence, this suggestion:

__Have one make function in the `QSR_Abstractclass` which calls a few well structured and purpose bound customised functions__

The pseudo python code for this could look like this:

```python
def make(self, *args, **kwargs):
        input_data, timestamps = set_input_data(**kwargs)
        ret = World_QSR_Trace(qsr_type=self._unique_id)
        parameters_dict = get_parameters(**kwargs)
        for p in qsrs_for:
            if check_duplicate(o1_name, o2_name):
                ret.add_qsr(lookup_function(o1_name, o2_name))
            else:
                ret.add_qsr(compute_qsr(parameters_dict, ...))
        ret = post_process(ret)
        return ret
```

Here are the main functions used:

**set_input_data** Quite self explanatory

```python
def set_input_data(**kwargs):
    input_data = kwargs["input_data"]
    timestamps = input_data.get_sorted_timestamps()
    return input_data, timestamps
```

**get_parameters** This function returns all the parameters necessary like `qsr_relations_and_values` or `quantisation_factor` in a dictionary and would be abstract so people have to implement it. But this could as well be standardised once all the deprecated stuff is gone.

**check_duplicate** Checks if the inverse object combination has been calculated already and return `True` if so. Default implementation would be:

```python
def check_duplicate(o1_name, o2_name):
    return False
```

this way you can override it to save time but you don't have to.

**lookup_function** This function turns the result for o1,o2 into o2,o1. Default implementation:

```python
def lookup_function(o1_name, o2_name):
    raise NotImplementedError
```

This way the user will be forced to override it if `check_duplicate` is overridden. Otherwise this will never be called and the make function just calculates all the possible combinations.

**compute_qsr** is where all the magic goes and what actual computes your QSR. This would be an abstract function, so people have to implement it.

**post_process** is for everything you have to do with the result after it has been calculated, e.g. the timstamp rectification of QTC. The default implementation would be:

```python
def post_process(qsr):
    return qsr
```

The reasoning behind all this, currently the make function has a lot of overhead and is not well structured or especially easy to read. By splitting it up into two mandatory (and a few optional functions  to speed up calculation or do post processing) this would be clearer and also easier to maintain. It would also enforce more standardisation which is always a good thing.

**_Edit:_** This change wouldn't break anything as the make function is currently overridden in every of the QRSs, therefore, the transition doesn't have to be abrupt. 

Opinions?

### LINKED ISSUE #137: Towards 0.2
Help needed.

[This branch](https://github.com/yianni/strands_qsr_lib/tree/towards-0.2) includes some changes that we have been discussing, mainly:
* restructuring the code to make it simpler for devs
* making --future the only option

Still pending are:
* @cdondrup QTCBS family has not been restructured; I have provided the abstractmethods that need to be implemented; can you please restructure it? I will provide more details below.
* @pet1330 Can you change the RCC relations according to PR #128 Sorry but it was not merged when I pulled master; shouldn't take long.

Some notes:
* `make` function is replaced by `make_world_qsr_trace`. This is the main function that a dev should implement and has a lot of the previous overhead removed.
* The overhead now is integrated in functions:
 * `_process_qsrs_for`
 * `_process_qsr_parameters_from_request_parameters`
 * `_postprocess_world_qsr_trace`
 * `_init_qsrs_for_default`
There are also new abstract classes:
* `QSR_Monadic_Abstractclass`
* `QSR_Dyadic_Abstractclass`
that also handle some of the common overhead.

PR that needs rejecting:
* #136 as default behaviour of dyadic relations is to return all possible combinations (i.e. including mirrors) see also file `combinations_and_permutations`
* #131 
* #128

Also I suggest blocking the remaining PRs till we get this sorted first.

Footnotes:
* argd and argprod are bugged, working on it.
* code far from cleaned up but can be done in parallel.
* `qsrs_for` not fully tested but with the new way it is much easier to change and debug to what we finally decide.

Any questions shoot.

Many thanks.

### PR DESCRIPTION
**Pull request by yianni**
This PR makes a LOT of changes towards the targets of 0.2.

Here is the list (hope I won't forget anything):
* QSR dictionary format is now standard (what was known as `--future`); old string format is no longer available
* code has been restructured and refactored to avoid duplication
* most methods/members have been refactored to protected/private scope as needed
* code cleanup with many deprecated functions removed
* timestamps of `World_Trace` (and hence of `World_QSR_Trace`) are now floats; no longer allowed alpha strings; numeric strings and integers still acceptable as they will be casted to floats
* New abstract classes `QSR_Monadic_Abstractclass` and  `QSR_Dyadic_Abstractclass` plus special cases (look in their corresponding files). All final import QSRs (i.e. non abstract) must inherit from one of these accordingly. There is no abstract class for Polyadic QSRs; if you need file an issue.
* The passing of `qsrs_for` has now changed. It can be done in the QSR namespace in `dynamic_args` or in the `for_all_qsrs` namespace again in `dynamic_args` with the QSR namespace taking precedence. Can be completely omitted for default behaviour. Old way has been deprecated and removed.
* All dyadic QSRs create by default combinations of the available objects, i.e. pairs including mirrors.
* You can now pass QSR parameters in the QSR namespace in `dynamic_args` or if applicable to all in the `for_all_qsrs` in `dynamic_args`.
* `include_missing_data` has been deprecated and removed; i.e. you won't get the same length of `World_QSR_Trace` as `World_Trace` if there are missing values like before where they would be filled in with empty `World_States`. This means there will be discontinuity in timestamps.
* The standalone and ros examples have been merged into one called `example.py`. By default it will run in pure python. If you want to run the example within ROS use `--ros` as argument in the command line.
* Provided MWE for usage and development of new QSRs.
* Wrapped `qsrlib_object_creation_test` in ROS.

Issues closed:
* closes #137 
* closes #134
* closes #127 
* closes #126 
* closes #122 
* closes #119 
* closes #118 
* closes #114 
* closes #113 
* closes #67 

Still need to verify:
* #112 

Some new issues to open that I noticed from my tests:
* Discuss whether QTCS is capable of supporting missing values (bypassing `custom_checks` seems to work, but whether results are correct or not is another question).
* Speed improvements to copy/invert QSR if mirror exists where applicable

Feel free to comment for more if you spot any and aren't critical that prevent merging of this PR.

### CODE REVIEW

**Comment by yianni** [comment]
Any volunteers to test this? IMO it should be merged before the school.

Also added a blocker tag so that to hold any other PRs before this one is merged.

**Comment by cdondrup** [comment]
I can test this tomorrow and have a look why qtc does not work with multiple any more... didn't test this earlier, sorry.

**Comment by yianni** [comment]
Leave the multiple test last... there might be other reasons that break the rest in multiple and simply crashes on QTC if it gets computed first.

In fact let me quickly check this now.

**Comment by yianni** [comment]
Yup it is the QTCS family only, and each one of the three variants gives a different error.

**Comment by cdondrup** [comment]
Haha, nice. I'll have a look tomorrow.

**Comment by yianni** [comment]
Latest commits provide MWE for LAMOR and for general.

Also fix a bug when `dynamic_args` are not passed in a request.

**Comment by yianni** [comment]
*doh* just saw accidentally your PR as I was not getting notifications. Anyway.

All work fine now... and actually works now with minimal data (2 objects 2 timestamps) as it was failing before for the same reason.

From my side I think all done...

Whoever testing it let me know when happy to merge.

**Comment by cdondrup** [comment]
Didn't have time today due to summer school preparations, sorry. My QTC tests work fine and if the QTC bug is fixed now, then everything should be OK. Can test it tomorrow during the lectures if you like.

**Comment by yianni** [comment]
No worries that's fine.

My tests have also worked fine with pretty much everything I tried except the pending issues mentioned in the patch notes.

There is nothing else to add from my side for this PR. Pending open issues that will remain are not critical and can be handled after the merge.

So yes give it a spin when you are free and let me know that is good to merge.

**Comment by yianni** [comment]
Thought of one last further simplification that I want to include. If you have started testing let me know and I will postpone. Otherwise, I will let you know when OK again to test.

**Comment by cdondrup** [comment]
Didn't start yet. Preping robots for school

**Comment by yianni** [comment]
And back at you. I really can't make the QSR development more compact I think (unless I write a program to write them).

Unfortunately, looking at the QTCS code the make_world_qsr_trace is too complex to fit any of the new prototypes. But that's OK as it can still inherit from the appropriate class and implement its own method.

When you are free please test it and let me know to merge.

The sooner the better for me so I will stop changing things. :)

**Comment by cdondrup** [comment]
I'll do it ASAP then ;)

**Comment by yianni** [comment]
Sorry, last change (I know I keep on saying that). Defintely can't think of making it simpler now. Just look the `qsr_new_mwe.py`. Don't even need a make now depending on where a QSR has inherited.

**Comment by yianni** [comment]
> I'll do it ASAP then ;)

Thanks :)

**Comment by cdondrup** [comment]
I can run the example client with all the QSRs + multiple and also my qtc tests pass. Not sure what else to test. I'd say it's good to merge.

**Comment by cdondrup** [comment]
Let me know if you want it re-released as 0.2 after this.

**Comment by yianni** [comment]
Maybe `dynamic_args` and `qsrs_for` but they have have worked for me, so probably no need.

Therefore, I will merge and yes please release 0.2. Any other pending issues that I have in mind are minimal, not critical and only internal to QSRlib developers.

**Comment by cdondrup** [comment]
I use qsrs_for in the qtc tests, so that should work fine.

**Comment by yianni** [comment]
OK great thanks. So many issues disappeared :+1: .

**Pull request merged**
