### PR TITLE
closes #48 and #45 added support to represent qsr fields as dictionaries, added support for ini files at start and at runtime

### LINKED ISSUE #48: [QSRlib] Change the qsr member from string to dictionary
I am really keen on changing the qsr field from default string to dictionary for various reasons, including better support of QSRs that consist of multiple singleton QSRs, being able to concat different QSRs etc.

Any thoughts/objections to that before I go ahead and do it?

### PR DESCRIPTION
**Pull request by yianni**
** ***NOTE UPDATE*** **

**Added support to represent qsr fields as dictionaries.**

The default is still strings. To enable this you need to set to the `request_message` constructor or in make `future=True`. To test it in the `ros_example_client` just pass `--future`.

I have updated the QSRs except from QTC as it is not possible without having the pending pull requests merged.

At some point I would like to deprecate the string representation. But, only when everyone is happy. So for future please use the dictionary format.

**Added support for ini files at startup and at runtime**
See example in `example_ros_client`, `arg_distance` qsr and `cfg/defaults.ini`

If somebody could test these please.

### CODE REVIEW

**Comment by cdondrup** [comment]
How are dictionaries handled in C++ clients? Never really did that but I imagine it to be hell. I prefer sticking with strings. If it is similar to what getting ros parameters namespaces is like (using xmlrpc), then it really is hell and unnecessarily complicated. In general I have to once again utter my concern about changing return types dynamically via a config file. This will lead to clients breaking.

**Comment by yianni** [comment]
Config file has nothing to do with changing return type. It's only for initializing parameters for interested QSRs at startup as well at runtime. So don't worry the config file does not do what you describe. Unfortunately, I cannot make two different pull requests from my repo... These two are separate issues.

In fact I am in agreement that they should not change in runtime and in fact it should not be encouraged to have multiple formats. In my opinion dictionaries are more flexible as it will allow you to do things like `qtc_qsr = {"qtca": "+", "qtcb": "0", ...}`, as well as if you wanted a lets say rcc_qtc then it will be much easier to combine them in one structure by concatenating the two structures into one resulting into something like `rcc_qtc = {"rcc": "dc", "qtca": "+", "qtcb": "0", ...}` for example.

How they are handled in c++, by [maps](http://www.cplusplus.com/reference/map/map/) most likely, although I would assume it wouldn't be possible to mix and match the types of the keys/values (not that it should be done in python either). But, I have a feeling that there will be many more problems as the whole return class structure of `world_qsr` contains dictionaries so this is hardly the only one to worry. If there are issues there then most likely some form of transform from python to c++ structure would be needed.

**Comment by yianni** [comment]
bump. Any volunteers to test this please? @cdondrup @pet1330

**Comment by cdondrup** [comment]
The new QSRs need to implement the new abstract function as well:

```
Traceback (most recent call last):
  File "/home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib/scripts/qsrlib_ros_server.py", line 44, in <module>
    srv = QSRlib_ROS_Server()
  File "/home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib/scripts/qsrlib_ros_server.py", line 25, in __init__
    self.qsrlib = QSRlib(active_qsrs)
  File "/home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib/src/qsrlib/qsrlib.py", line 94, in __init__
    self.__set_qsrs_active(qsrs_active)
  File "/home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib/src/qsrlib/qsrlib.py", line 127, in __set_qsrs_active
    self.__qsrs_active[qsr_type] = class_name()
TypeError: Can't instantiate abstract class QSR_Cone_Direction_Bounding_Boxes_Centroid_2D with abstract methods custom_set_from_ini
```

**Comment by cdondrup** [comment]
After adding the new function to the cone class, it seems to work. Regarding the dict results:

```
cdondrup@calculon:~/ros_ws/src/strands_qsr_lib
$ rosrun qsr_lib example_ros_client.py arg_distance --future
arg_distance request was made at  2015-05-14 15:36:54.689023 and received at None and computed at 2015-05-14 15:36:54.693576
---
Response is:
0: o1,o2:{'argd': '0'}; o1,o3:{'argd': '2'}; o2,o3:{'argd': '2'}; 
1: o1,o2:{'argd': '1'}; o1,o3:{'argd': '2'}; o2,o3:{'argd': '2'}; 
2: o1,o2:{'argd': '2'}; o1,o3:{'argd': '2'}; o2,o3:{'argd': '2'};
```

I find it a bit unintuitive that the identifier is different from the one I use in the client. Maybe we should come up with a way of unifying them so we don't use `arg_distance` here and `argd` there. Maybe we should use the full identifier stings from the qsrlib.py. Or have a dictionary that does some mapping from short names to full names in the abstract class.

I'll test the config file stuff now.

**Comment by yianni** [comment]
@cdondrup Thanks for the quick test. It has been added (see here)[https://github.com/strands-project/strands_qsr_lib/pull/49/files#diff-bfc6cfc3f7710226c0bd1d9b94a57304R34]

How do you fetch the pull-request for testing?

Can you please try with the following?
`git fetch <HOW_you_named_upstream> pull/49/head:49`
then
`git checkout 49`

**Comment by cdondrup** [comment]
I usually do what github suggests: 
```
git checkout -b yianni-master master
git pull git://github.com/yianni/strands_qsr_lib.git master
```

**Comment by yianni** [comment]
> I find it a bit unintuitive that the identifier is different from the one I use in the client. Maybe we should come up with a way of unifying them so we don't use arg_distance here and argd there. Maybe we should use the full identifier stings from the qsrlib.py. Or have a dictionary that does some mapping from short names to full names in the abstract class.

Agree that something more unifying is needed. I wouldn't like the full name in the dict though, too painful and makes code/results reading painful.

**Comment by cdondrup** [comment]
The missing function call is actually in the new cone qsr. The one you linked is in RCC8. Got that one, cone is still missing though.

**Comment by yianni** [comment]
> I usually do what github suggests:
> 
> git checkout -b yianni-master master
> git pull git://github.com/yianni/strands_qsr_lib.git master

That would work too and result to the same if the pull-request was made from fork/master. The one I have written is from the upstream/pull_request and doesn't require knowing repo/branch where the pull request is coming from.

**Comment by yianni** [comment]
> The missing function call is actually in the new cone qsr. The one you linked is in RCC8. Got that one, cone is still missing though.

Ah yes. Will update and repush, give me a few mins.

**Comment by cdondrup** [comment]
I can't really comment if the values I set in the ini influence the arg_distance relation correctly, but they do influence it and the return as a dictionary works as well. Also tested the new commit for the cone qsr.

I'd say merge and we try to find a unifying way once the dict becomes standard. Since the service call requires the full string to identify the qsr I would find it logical that the result contains the same string as the key. We could define constants in the qsrlib_ros_client to make it more readable but I think the string used for the request should also be used in the result. Everything else is confusing.

**Comment by yianni** [comment]
> I can't really comment if the values I set in the ini influence the arg_distance relation correctly, but they do influence it and the return as a dictionary works as well. Also tested the new commit for the cone qsr.

I probably should have left my dbg print statement in it.
`print(qsr_relations_and_values)` [before this line](https://github.com/strands-project/strands_qsr_lib/pull/49/files#diff-a9f90ddfb934e566d01b346d2492b42cR73)


> 
> I'd say merge and we try to find a unifying way once the dict becomes standard. Since the service call requires the full string to identify the qsr I would find it logical that the result contains the same string as the key. We could define constants in the qsrlib_ros_client to make it more readable but I think the string used for the request should also be used in the result. Everything else is confusing.

OK, cool I will merge... Whoever wants to use/update this functionality, it is there now.

**Comment by yianni** [comment]
@cdondrup oh by the way. QTC is the only one that does not return dict with --future. Had a look in your code but wasn't clear some things so didn't want to edit half-blind. Will open an issue about it so that we won't forget. OK?

**Comment by cdondrup** [comment]
Just figured, now every time the service is called a config file might be read. How about leaving that to the client and just passing the content as a string. If you have many calls in a live system reading the file all the time is an unnecessary operation.

**Comment by yianni** [comment]
Is it? I thought I had it so that if no config file is passed then the ones at setup/creation are used. It shouldn't happen [see here](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/src/qsrlib_qsrs/qsr_arg_relations_distance.py#L66)

Basically passing an ini is optional, if none is passed the ones at creation setup will be used.

**Comment by yianni** [comment]
@cdondrup OK test it and it's fine it only reads at init of the class and then only when an ini filename is passed. So all good.

**Pull request merged**
