### PR TITLE
regional algebra 'ra' new QSR

### PR DESCRIPTION
**Pull request by yianni**
Implementation of Regional Algebra (`ra` unique id).

Both 2D and 3D is supported but it is limited to only 2D at the moment due to a constraint posed by `QSR_Abstractclass`.

No point writing the unittests till it is confirmed that it works correctly.

If someone could test it therefore, I think @PDuckworth has experience with Allen relations and if you could please do it (hence assigned to him). If anyone also wants to test it please go ahead.

For the tests [this table](https://en.wikipedia.org/wiki/Allen%27s_interval_algebra#Relations) describing the relations might be of help.

### CODE REVIEW

**Comment by yianni** [comment]
It's OK the failing. It's the mutliple test failing which is expected as it needs updating once the correctness of RA is validated.

**Comment by PDuckworth** [comment]
Yep - seems to match the table fine. 
I added some extra timepoints, and moved the BBs around.

**Comment by yianni** [comment]
Thanks. Will merge then.

**Comment by PDuckworth** [comment]
When X meets Y, if you are using this for discrete time steps, you'll need to -1 from the end of one interval. 
i.e. This doesn't match the Allen intervals in the QSTAG code.

**Comment by yianni** [comment]
I will open a separate issue. Depends on the unit step though as we discussed ;)

**Pull request merged**
