### PR TITLE
Fixed removing duplicates

### PR DESCRIPTION
**Pull request by pet1330**
stopped filtering duplicates in qsrs_for_default function and assigned inverse duplicates the same value as their counterparts, this way you get a result for all possible qsr object pair combinations, rather than getting the result for only one of the two combinators which is inconsistent.

### CODE REVIEW

**Comment by yianni** [comment]
@cdondrup commented in #137 that this PR computes the qsrs_for only once... but can't see that on the code other than it returns also mirrors. If that's the change of this PR, it's OK cause the dev branch does the same by default and using python's tools which hopefully are optimized.

**Comment by cdondrup** [comment]
Yes it creates the inverse objects combinations (if no `qsrs_for` are given) and looks them up. Previous behaviour was generating `argd` for `o1,o2` but not for `o2,o1` which led to very non-deterministic behaviour.

**Comment by yianni** [comment]
I see. OK, it's removed in my latest commit in my branch.. can be added later as there are more urgent matters at the moment and needs to be done for more of them... so there might be a way to create a method for it in parent class. But, later...

**Comment by cdondrup** [comment]
As long as it creates all possible combinations when no `qsrs_for` is given, I'm happy ;)

**Comment by yianni** [comment]
Yes mirrors now is the default behaviour for all dyadic qsrs.

**Comment by yianni** [comment]
Will reject this one for now... towards-0.2 branch has mirrors as default for dyadic qsrs. The speed improvement can be applied later as it needs to be done for all related and might be a better way to include a function in parent to avoid code replication.

**Comment by cdondrup** [comment]
:+1:

**Pull request closed without merging**
