### PR TITLE
Cone Direction QSR added

### PR DESCRIPTION
**Pull request by pet1330**
Adds a QSR which calculates the direction of object two compared to object one using the following:
```
["north", "north-east", "east", "south-east", "south", "south-west", "west", "north-west", "same", "unknown"]
```

### CODE REVIEW

**Comment by yianni** [comment]
@pet1330 with respect to what is north, east, south, west?

**Comment by yianni** [comment]
also o1o2: "north" means "o2 is north of o1". Is that your intention? Cause that is different from the way that RCC8 is.

My view is that RCC8 way is the right one, ie o1o2: north should mean "o1 is to the north of o2".

Wait a sec and I will upload the dbg script also.

**Comment by pet1330** [comment]
When bb2 is above bb1 then it returns north. As bb2 is north of bb1. This may however, depend on which way around your coordinate system is...

**Comment by pet1330** [comment]
In that case they the the labels just need to be reordered, I'll do that now :)

**Comment by yianni** [comment]
> This may however, depend on which way around your coordinate system is...

Yes it does depends on the coordinate system.

**Comment by cdondrup** [comment]
So the result would have to include the `frame_id`?! Otherwise, this type of QSR is pointless imho.

**Comment by pet1330** [comment]
The issue with that is that the library is not just used with ROS...

**Comment by cdondrup** [comment]
Somehow the origin of the coordinate system has to be encoded, doesn't it? I have never used this QSR before and there might be some logic behind this... Maybe just knowing the position of the objects in relation to each other is enough... Just put my 2 cents in ;)

**Comment by yianni** [comment]
But yes that was a point I was trying to make... North is always north in human world... In this QSR north depends on the coordinate system of the encoding... If the point of the QSR is to know the relational position of two objects with respect to each other, then it is fine. But, if north here means human world north, then there is a problem and not really easily solvable.

Which one of the two is it?

**Comment by yianni** [comment]
> The issue with that is that the library is not just used with ROS...

What do you mean?

**Comment by pet1330** [comment]
North for me was the direction the human was initially facing which for me was in the direction of an increasing Y value. 
<pre>
    8 |
    7 |
    6 |            bb2
    5 |
Y   4 |
    3 |            bb1
    2 |
    1 |
    0 |_ _ _ _ _ _ _ _ _ _ _ _ _
        0 1 2 3 4 5 6 7 8
                        X
</pre>
So for example, bb1 (6, 3)   bb2(6,6)  making bb2 north of bb1. However, this changes when the coordinate system changes...

**Comment by yianni** [comment]
Yes it does. If you had a camera on top of the human then the human-recorded data would be different than the camera-recorded one as they use different coordinate frames, and hence also the relations.

My feeling is that it is fine as it is, but it should be noted that it provides this relations according to the coordinate system (of course). Also tested and works, but before merged better speak with @cdondrup about this and see what you want to do with this QSR.

**Comment by pet1330** [comment]
> he issue with that is that the library is not just used with ROS...
> What do you mean?

That was in reply to @cdondrup saying:

> So the result would have to include the frame_id?! Otherwise, this type of QSR is pointless imho.

The library can be used with or without ROS, if you are using it without ROS, then you will not have a frame_id to pass in.

**Comment by yianni** [comment]
> then you will not have a frame_id to pass in.

`frame_id` is just a string. You can always pass it in `kwargs` if needed by the server. There is no mechanism from the top of my head to return it back to the client, but shouldn't the client know this since it is the one making the request?

**Comment by pet1330** [comment]
I think it might be easier to just keep a constant coordinate system, with an increase in Y being North. Then the client can transform to and from the coordinate system they want before making the request. That's would simplify the whole thing and make the responds much clearer.

**Comment by yianni** [comment]
@cdondrup @pet1330 Unless there are any objections I will merge this later in the afternoon. If there are please post here so I won't and please discuss/resolve them.

**Comment by cdondrup** [comment]
No issues from my side.

**Comment by pet1330** [comment]
Go for it :+1:

**Pull request merged**
