### PR TITLE
Adding a particle filter for QSRs to the prob_rep library

### PR DESCRIPTION
**Pull request by cdondrup**
Looking at the example of my work, I need a way to online classify interactions between humans and the robot and would also like to predict the next most likely state to choose the correct robot behaviour. This PR adds a particle filter that works on arbitrary QSRs to do exactly that. The particle filter needs a markov model of an interaction, a noise model for the observations, and a state look-up table with all possible states. There can be multiple different markov models and observation models which are all handled at the same time. The particle filter will classify the most likely model and also track the current state of the underlying markov model.

As an input, you can use the hmm, i.e. the emission matrix as the noise model and the transition matrix as the markov model. If there is not enough data to train the emissions properly, you can also create a noise model manually as done in [qtc_model_creation.py](https://github.com/cdondrup/strands_qsr_lib/blob/6a214d7873a06f89b4d79616a6357f844cf7bfb5/qsr_prob_rep/src/qsrrep_utils/qtc_model_creation.py). Essentially, both matrices have to have the same dimensions NxN where for the markov model M_{j,i} describes the probability of state `j` to transition to state `i` and the Observation model for the noise O_{j,i} represents the probability with which state `i` can be observed when state `j` has been predicted.

The particle filter, like the hmm, follows the same usage approach:
* Create an instance of the correct Request class
* Call the ros_client

So all the complexity of the underlying service call is completely hidden from the user. A simple bit of python code:

```python
p = ROSClient().call_service(
  PfRepRequestUpdate(
    uuid="lksajd89ewkmdeaifd", # PF identifier
    observation="-,-,+,+" # Current observation
  )
)
```

calls the correct service based on the request class and generates the output for you.

For a more detailed example, have a look at the two example clients.

Other changes:
* The whole infrastructure of how the services are created and how the correct function is called when a service is called has changed to make it easier to develop and integrate new representations.
 * services now have different namespace for the different representations, e.g. `~/hmm/create`
* The hmm now has a generic hmm which accepts a look-up table for the states and a pre-training emission and transition matrix.
* The hmm now allows pseudo transitions
* Added scripts to create particle filter models from an existing hmm
* Added example files for the creation of a particle filter

The particle filter has been tested in simulation. The generic hmm still needs a bit of testing but maybe @pet1330 can do that.

TODO: Documentation needs update or is entirely missing for some functions.

### CODE REVIEW

**Comment by yianni** [comment]
I am happy for it to be merged since the rostests have passed. But, at the moment I am really busy to give it a dedicated spin. If you want someone to give it an extensive test then if anyone can volunteer or maybe someone from Lincoln can do it as it will be easier to reach you for whatever reason needed during the test.

**Comment by pet1330** [comment]
I'll be using this soon, so I'll give it a proper test just after Christmas :smile:

**Comment by cdondrup** [comment]
I didn't have time to implement tests for this before I left for holiday; Will do when I'm back. I am confident that @pet1330 will find the possible errors in there ;) Thanks!

**Comment by marc-hanheide** [comment]
@pet1330 did you test this? Can it be merged?

**Comment by pet1330** [comment]
Not yet, it's on my todo list...

**Comment by cdondrup** [comment]
Added some very simple tests for the particle filter just checking that it works but not if the actual results make sense.

**Comment by pet1330** [comment]
We found a couple of issues with it today, but these are now  all resolved with the above commits and can now be merged :)

**Comment by cdondrup** [comment]
Since the service definition of the qsr_pro_rep lib has changed with this PR, the next release version should be 0.3 @yianni

**Pull request merged**
