### PR TITLE
cone_direction now complies with --future (closes #58)

### LINKED ISSUE #58: [cone_direction] Comply with --future

### PR DESCRIPTION
**Pull request by yianni**

### CODE REVIEW

**Comment by yianni** [comment]
@pet1330 please test when you have a moment

**Comment by pet1330** [comment]
It works, but for consistency, you may want to change the "cone_direction" option [here] (https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/scripts/example_ros_client.py#L30) and [here](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/scripts/example_standalone#L22) to coneDir as well.

**Comment by yianni** [comment]
@pet1330 merge?

**Comment by cdondrup** [comment]
@pet1330 is on holiday. Did a quick test, seems to work.

**Pull request merged**
