### PR TITLE
Moved qtc parameters to service call

### LINKED ISSUE #53: [QTC] move custom arguments from object creation to service call
Currently the `quantisation_factor`, `validate`, `no_collapse`, and `distance_threshold` are added to each object. This is unnecessary and could go into the service calls using the `ini` argument if this would support strings or as separate arguments.

### PR DESCRIPTION
**Pull request by cdondrup**
Using dynamic_args and the newly created field 'parameters'.
Should be fully backwards compatible with the option of removing this later on.

Closes #53

### CODE REVIEW

**Comment by yianni** [comment]
Thanks. Works fine, although not sure why you need a `parameters` field in the dictionary as you can lay the parameters straight in the `dynamic_args` dictionary. If it is to "protect" or "compact" the qtcs parameters then I would rename the key of that to "qtcs_parameters". Then again if you are thinking of having a "generic" parameters field depending on qsr, then it is pretty redundant cause `dynamic_args = parameter` will do exactly that.

Overall I think it will create confusion cause the `dynamic_args` is exactly for passing custom_args of each qsr, there is no need for dictionary nesting, and if it is overloaded in the example it is to make all qsrs runnable as an example.

**Comment by cdondrup** [comment]
I was just following the example with the `qsr_values_and_relations` (or whatever it was called). Having them directly under the dynamic_args works for me as well. I can change that while resolving the conflicts if you like.

**Comment by yianni** [comment]
Basically if you could please do the following:
'''python
qsrlib_request_message = QSRlib_Request_Message(which_qsr=which_qsr, input_data=world, include_missing_data=True,
                                                    dynamic_args=dynamic_args,
                                                    future=args.future)
'''
Replace `parameters` with `dynamic_args, I can update the "broken" ones in the example. You will also need to update QTCS code I assume from `kwargs["dynamic_args"]["parameters"][<something>]` to `kwargs["dynamic_args"][<something>]`.

**Comment by cdondrup** [comment]
Will do asap.

**Comment by yianni** [comment]
> I was just following the example with the qsr_values_and_relations (or whatever it was called). Having them directly under the dynamic_args works for me as well. I can change that while resolving the conflicts if you like.

I see. Yes, that is misleading cause the `qsr_values_and_relations` is actually the parameter whose data happens to be a dictionary.

**Comment by cdondrup** [comment]
Hope this is how you meant it @yianni 
Please have another look. I tried all the relations in the example client and all of them worked without throwing errors. Can't tell if the actual results were correct though.

**Comment by yianni** [comment]
Great. Thanks. Need to fix for one of them (MOS) but that's OK, I will merge this and make an issue for me not to forget. Values should be correct I think as I don't see anything else to have changed in the core of the code and a quick test with `quantisation_factor=100` and `no_collapse` changes its values correctly.

**Pull request merged**
