### PR TITLE
Adding new QSR qtcbcs_argprobd - Version 0.2

### PR DESCRIPTION
**Pull request by cdondrup**
Works like qtcbcs but using the abstract probabilities of argprobd. Also had to make a few variables and functions protected instead of private.

See #125 for more detailed explanation.

### CODE REVIEW

**Comment by yianni** [comment]
How does it compare to #151? I smell possible conflicts.

**Comment by cdondrup** [comment]
Didn't check that one... too many changed files ;) Just merge this PR after #151 and if there are conflicts, I'll rebase.

**Comment by marc-hanheide** [comment]
retest this please

**Comment by cdondrup** [comment]
I'll resolve the conflicts asap. Just won't be that soon... but since I'm the only one using this shouldn't be a problem.

**Comment by cdondrup** [comment]
Not used any more, will close for now.

**Pull request closed without merging**
