### PR TITLE
Allows to call by QSR shortname now

### PR DESCRIPTION
**Pull request by yianni**
- Allows to call by QSR shortname, by automatically registering the QSR shortnames (offers protection for ducplications)
- `QSRlib.__active_qsrs` removed
- `QSRlib.__const_qsrs_available` renamed to `__qsrs`
- Removed unused arguments

### CODE REVIEW

**Comment by cdondrup** [comment]
I like this. "Removes" one of the magic strings.
Works for me.

You might want to think about using the new call in the example client as well to get rid of some of the overhead.

**Comment by yianni** [comment]
> You might want to think about using the new call in the example client as well to get rid of some of the overhead.

Will do that at some point along with #67

**Comment by yianni** [comment]
OK to merge? Need it to rebase the changes with the `unique_id`.

**Comment by yianni** [comment]
> Works for me.

Missed that.

**Pull request merged**
