### PR TITLE
Resolving mini issues

### PR DESCRIPTION
**Pull request by yianni**
Some of the mini-issues in the 0.2 meta.

### CODE REVIEW

**Comment by yianni** [comment]
When someone has time to test this PR.

**Comment by yianni** [comment]
If the testing of this would involve running the example_extended with multiple then not much point anymore as it is already run by the new rostests.

If that's the case can I merge?

**Comment by yianni** [comment]
Blocked till rostests are working in jenkins.

**Comment by cdondrup** [comment]
This is all related to https://github.com/strands-project/strands_ci/issues/13 I guess?! @marc-hanheide should know.

**Comment by yianni** [comment]
Any chance of this getting merged? Given that jenkins rostests are currently unreliable till they are resolved you can still test it by running the rostests locally, I usually use the following:
```bash
catkin_make run_tests_qsr_lib_rostest
```
from catkin workspace source folder.

[See here for details.](http://docs.ros.org/indigo/api/catkin/html/howto/format1/run_tests.html)

**Comment by cdondrup** [comment]
All tests pass on my machine as well. They do use a lot of RAM (several python processes (>5) using around 1GB each) and a lot of time but pass.

**Comment by yianni** [comment]
Are you sure? I'm getting the following:
```bash
build/test_results/qsr_prob_rep/rostest-tests_hmm_tester.xml: 1 tests, 0 errors, 1 failures
Summary: 102 tests, 0 errors, 1 failures
```

**Comment by yianni** [comment]
argh hold on getting more errors now for some reason. let me investigate. will tell you when everything on my machine.

**Comment by cdondrup** [comment]
If I run the command you posted, I don't get a nice summary like this and it does not run as many tests. But all the tests it runs, pass:

```
cdondrup@calculon:~/ros_ws
$ catkin_make run_tests_qsr_lib_rostest
Base path: /home/cdondrup/ros_ws
Source space: /home/cdondrup/ros_ws/src
Build space: /home/cdondrup/ros_ws/build
Devel space: /home/cdondrup/ros_ws/devel
Install space: /home/cdondrup/ros_ws/install
####
#### Running command: "make cmake_check_build_system" in "/home/cdondrup/ros_ws/build"
####
####
#### Running command: "make run_tests_qsr_lib_rostest -j8 -l8" in "/home/cdondrup/ros_ws/build"
####
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib --package=qsr_lib --results-filename tests_qsrlib_object_creation_tester.xml --results-base-dir /home/cdondrup/ros_ws/build/test_results /home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib/tests/qsrlib_object_creation_tester.test 
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib --package=qsr_lib --results-filename tests_rcc8_tester.xml --results-base-dir /home/cdondrup/ros_ws/build/test_results /home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib/tests/rcc8_tester.test 
-- run_tests.py: execute commands
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib --package=qsr_lib --results-filename tests_qtc_tester.xml --results-base-dir /home/cdondrup/ros_ws/build/test_results /home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib/tests/qtc_tester.test 
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib --package=qsr_lib --results-filename tests_argprobd_tester.xml --results-base-dir /home/cdondrup/ros_ws/build/test_results /home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib/tests/argprobd_tester.test 
... logging to /home/cdondrup/.ros/log/rostest-calculon-25076.log
... logging to /home/cdondrup/.ros/log/rostest-calculon-25080.log
... logging to /home/cdondrup/.ros/log/rostest-calculon-25079.log
... logging to /home/cdondrup/.ros/log/rostest-calculon-25074.log
[ROSUNIT] Outputting test results to /home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_rcc8_tester.xml
[ROSUNIT] Outputting test results to /home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_qsrlib_object_creation_tester.xml
[ROSUNIT] Outputting test results to /home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_argprobd_tester.xml
[ROSUNIT] Outputting test results to /home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_qtc_tester.xml
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib --package=qsr_lib --results-filename tests_mos_tester.xml --results-base-dir /home/cdondrup/ros_ws/build/test_results /home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib/tests/mos_tester.test 
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib --package=qsr_lib --results-filename tests_mwe_tester.xml --results-base-dir /home/cdondrup/ros_ws/build/test_results /home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib/tests/mwe_tester.test 
... logging to /home/cdondrup/.ros/log/rostest-calculon-25248.log
... logging to /home/cdondrup/.ros/log/rostest-calculon-25247.log
[ROSUNIT] Outputting test results to /home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_mos_tester.xml
[ROSUNIT] Outputting test results to /home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_mwe_tester.xml
testqsrlib_object_creation_tester ... ok

[ROSTEST]-----------------------------------------------------------------------

[qsr_lib.rosunit-qsrlib_object_creation_tester/test][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 1
 * ERRORS: 0
 * FAILURES: 0

rostest log file is in /home/cdondrup/.ros/log/rostest-calculon-25074.log
-- run_tests.py: verify result "/home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_qsrlib_object_creation_tester.xml"
Built target run_tests_qsr_lib_rostest_tests_qsrlib_object_creation_tester.test
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib --package=qsr_lib --results-filename tests_argd_tester.xml --results-base-dir /home/cdondrup/ros_ws/build/test_results /home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib/tests/argd_tester.test 
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib --package=qsr_lib --results-filename tests_coneDir_tester.xml --results-base-dir /home/cdondrup/ros_ws/build/test_results /home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib/tests/coneDir_tester.test 
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib --package=qsr_lib --results-filename tests_qtcbs_tester.xml --results-base-dir /home/cdondrup/ros_ws/build/test_results /home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib/tests/qtcbs_tester.test 
... logging to /home/cdondrup/.ros/log/rostest-calculon-25373.log
... logging to /home/cdondrup/.ros/log/rostest-calculon-25380.log
... logging to /home/cdondrup/.ros/log/rostest-calculon-25389.log
[ROSUNIT] Outputting test results to /home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_argd_tester.xml
[ROSUNIT] Outputting test results to /home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_coneDir_tester.xml
[ROSUNIT] Outputting test results to /home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_qtcbs_tester.xml
testqtc_tester ... ok

[ROSTEST]-----------------------------------------------------------------------

[qsr_lib.rosunit-qtc_tester/test_qtcb][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcb_inverse][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcb_multiple_objects][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcb_nocollapse][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcb_nocollapse_inverse][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcbc][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcbc_inverse][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcbc_multiple_objects][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcbc_nocollapse][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcbc_nocollapse_inverse][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcc][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcc_inverse][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcc_multiple_objects][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcc_nocollapse][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcc_nocollapse_inverse][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 15
 * ERRORS: 0
 * FAILURES: 0

rostest log file is in /home/cdondrup/.ros/log/rostest-calculon-25079.log
-- run_tests.py: verify result "/home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_qtc_tester.xml"
Built target run_tests_qsr_lib_rostest_tests_qtc_tester.test
Scanning dependencies of target run_tests_qsr_lib_rostest_tests_qtccs_tester.test
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib --package=qsr_lib --results-filename tests_qtccs_tester.xml --results-base-dir /home/cdondrup/ros_ws/build/test_results /home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib/tests/qtccs_tester.test 
... logging to /home/cdondrup/.ros/log/rostest-calculon-25602.log
[ROSUNIT] Outputting test results to /home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_qtccs_tester.xml
testargd_tester ... ok

[ROSTEST]-----------------------------------------------------------------------

[qsr_lib.rosunit-argd_tester/test_defaults][passed]
[qsr_lib.rosunit-argd_tester/test_qsrs_for_global_namespace][passed]
[qsr_lib.rosunit-argd_tester/test_qsrs_for_qsr_namespace][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 3
 * ERRORS: 0
 * FAILURES: 0

rostest log file is in /home/cdondrup/.ros/log/rostest-calculon-25373.log
-- run_tests.py: verify result "/home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_argd_tester.xml"
Built target run_tests_qsr_lib_rostest_tests_argd_tester.test
testmwe_tester ... ok

[ROSTEST]-----------------------------------------------------------------------

[qsr_lib.rosunit-mwe_tester/test_defaults][passed]
[qsr_lib.rosunit-mwe_tester/test_floats][passed]
[qsr_lib.rosunit-mwe_tester/test_qsrs_for_global_namespace][passed]
[qsr_lib.rosunit-mwe_tester/test_qsrs_for_qsr_namespace][passed]
[qsr_lib.rosunit-mwe_tester/test_with_bounding_boxes][passed]
[qsr_lib.rosunit-mwe_tester/test_without_bounding_boxes][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 6
 * ERRORS: 0
 * FAILURES: 0

rostest log file is in /home/cdondrup/.ros/log/rostest-calculon-25247.log
-- run_tests.py: verify result "/home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_mwe_tester.xml"
Built target run_tests_qsr_lib_rostest_tests_mwe_tester.test
testconeDir_tester ... ok

[ROSTEST]-----------------------------------------------------------------------

[qsr_lib.rosunit-coneDir_tester/test_defaults][passed]
[qsr_lib.rosunit-coneDir_tester/test_floats][passed]
[qsr_lib.rosunit-coneDir_tester/test_qsrs_for_global_namespace][passed]
[qsr_lib.rosunit-coneDir_tester/test_qsrs_for_qsr_namespace][passed]
[qsr_lib.rosunit-coneDir_tester/test_with_bounding_boxes][passed]
[qsr_lib.rosunit-coneDir_tester/test_without_bounding_boxes][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 6
 * ERRORS: 0
 * FAILURES: 0

rostest log file is in /home/cdondrup/.ros/log/rostest-calculon-25380.log
-- run_tests.py: verify result "/home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_coneDir_tester.xml"
Built target run_tests_qsr_lib_rostest_tests_coneDir_tester.test
testmos_tester ... ok

[ROSTEST]-----------------------------------------------------------------------

[qsr_lib.rosunit-mos_tester/test_custom][passed]
[qsr_lib.rosunit-mos_tester/test_defaults][passed]
[qsr_lib.rosunit-mos_tester/test_floats][passed]
[qsr_lib.rosunit-mos_tester/test_q_factor][passed]
[qsr_lib.rosunit-mos_tester/test_qsrs_for_global_namespace][passed]
[qsr_lib.rosunit-mos_tester/test_qsrs_for_qsr_namespace][passed]
[qsr_lib.rosunit-mos_tester/test_with_bounding_boxes][passed]
[qsr_lib.rosunit-mos_tester/test_without_bounding_boxes][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 8
 * ERRORS: 0
 * FAILURES: 0

rostest log file is in /home/cdondrup/.ros/log/rostest-calculon-25248.log
-- run_tests.py: verify result "/home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_mos_tester.xml"
Built target run_tests_qsr_lib_rostest_tests_mos_tester.test
testrcc8_tester ... ok

[ROSTEST]-----------------------------------------------------------------------

[qsr_lib.rosunit-rcc8_tester/test_custom][passed]
[qsr_lib.rosunit-rcc8_tester/test_defaults][passed]
[qsr_lib.rosunit-rcc8_tester/test_floats][passed]
[qsr_lib.rosunit-rcc8_tester/test_q_factor][passed]
[qsr_lib.rosunit-rcc8_tester/test_qsrs_for_global_namespace][passed]
[qsr_lib.rosunit-rcc8_tester/test_qsrs_for_qsr_namespace][passed]
[qsr_lib.rosunit-rcc8_tester/test_with_bounding_boxes][passed]
[qsr_lib.rosunit-rcc8_tester/test_without_bounding_boxes][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 8
 * ERRORS: 0
 * FAILURES: 0

rostest log file is in /home/cdondrup/.ros/log/rostest-calculon-25076.log
-- run_tests.py: verify result "/home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_rcc8_tester.xml"
Built target run_tests_qsr_lib_rostest_tests_rcc8_tester.test
testargprobd_tester ... ok

[ROSTEST]-----------------------------------------------------------------------

[qsr_lib.rosunit-argprobd_tester/test_defaults][passed]
[qsr_lib.rosunit-argprobd_tester/test_qsrs_for_global_namespace][passed]
[qsr_lib.rosunit-argprobd_tester/test_qsrs_for_qsr_namespace][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 3
 * ERRORS: 0
 * FAILURES: 0

rostest log file is in /home/cdondrup/.ros/log/rostest-calculon-25080.log
-- run_tests.py: verify result "/home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_argprobd_tester.xml"
Built target run_tests_qsr_lib_rostest_tests_argprobd_tester.test
Scanning dependencies of target run_tests_qsr_lib_rostest_tests_rcc2_tester.test
Scanning dependencies of target run_tests_qsr_lib_rostest_tests_rcc3_tester.test
Scanning dependencies of target run_tests_qsr_lib_rostest_tests_multiple_tester.test
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib --package=qsr_lib --results-filename tests_rcc3_tester.xml --results-base-dir /home/cdondrup/ros_ws/build/test_results /home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib/tests/rcc3_tester.test 
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib --package=qsr_lib --results-filename tests_rcc2_tester.xml --results-base-dir /home/cdondrup/ros_ws/build/test_results /home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib/tests/rcc2_tester.test 
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib --package=qsr_lib --results-filename tests_multiple_tester.xml --results-base-dir /home/cdondrup/ros_ws/build/test_results /home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib/tests/multiple_tester.test 
... logging to /home/cdondrup/.ros/log/rostest-calculon-25763.log
... logging to /home/cdondrup/.ros/log/rostest-calculon-25765.log
... logging to /home/cdondrup/.ros/log/rostest-calculon-25767.log
[ROSUNIT] Outputting test results to /home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_rcc3_tester.xml
[ROSUNIT] Outputting test results to /home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_rcc2_tester.xml
[ROSUNIT] Outputting test results to /home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_multiple_tester.xml
testrcc2_tester ... ok

[ROSTEST]-----------------------------------------------------------------------

[qsr_lib.rosunit-rcc2_tester/test_custom][passed]
[qsr_lib.rosunit-rcc2_tester/test_defaults][passed]
[qsr_lib.rosunit-rcc2_tester/test_floats][passed]
[qsr_lib.rosunit-rcc2_tester/test_q_factor][passed]
[qsr_lib.rosunit-rcc2_tester/test_qsrs_for_global_namespace][passed]
[qsr_lib.rosunit-rcc2_tester/test_qsrs_for_qsr_namespace][passed]
[qsr_lib.rosunit-rcc2_tester/test_with_bounding_boxes][passed]
[qsr_lib.rosunit-rcc2_tester/test_without_bounding_boxes][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 8
 * ERRORS: 0
 * FAILURES: 0

rostest log file is in /home/cdondrup/.ros/log/rostest-calculon-25765.log
-- run_tests.py: verify result "/home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_rcc2_tester.xml"
Built target run_tests_qsr_lib_rostest_tests_rcc2_tester.test
Scanning dependencies of target run_tests_qsr_lib_rostest_tests_qtcbcs_tester.test
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib --package=qsr_lib --results-filename tests_qtcbcs_tester.xml --results-base-dir /home/cdondrup/ros_ws/build/test_results /home/cdondrup/ros_ws/src/strands_qsr_lib/qsr_lib/tests/qtcbcs_tester.test 
... logging to /home/cdondrup/.ros/log/rostest-calculon-25917.log
[ROSUNIT] Outputting test results to /home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_qtcbcs_tester.xml
testrcc3_tester ... ok

[ROSTEST]-----------------------------------------------------------------------

[qsr_lib.rosunit-rcc3_tester/test_custom][passed]
[qsr_lib.rosunit-rcc3_tester/test_defaults][passed]
[qsr_lib.rosunit-rcc3_tester/test_floats][passed]
[qsr_lib.rosunit-rcc3_tester/test_q_factor][passed]
[qsr_lib.rosunit-rcc3_tester/test_qsrs_for_global_namespace][passed]
[qsr_lib.rosunit-rcc3_tester/test_qsrs_for_qsr_namespace][passed]
[qsr_lib.rosunit-rcc3_tester/test_with_bounding_boxes][passed]
[qsr_lib.rosunit-rcc3_tester/test_without_bounding_boxes][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 8
 * ERRORS: 0
 * FAILURES: 0

rostest log file is in /home/cdondrup/.ros/log/rostest-calculon-25763.log
-- run_tests.py: verify result "/home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_rcc3_tester.xml"
Built target run_tests_qsr_lib_rostest_tests_rcc3_tester.test
testqtcbs_tester ... ok

[ROSTEST]-----------------------------------------------------------------------

[qsr_lib.rosunit-qtcbs_tester/test_defaults][passed]
[qsr_lib.rosunit-qtcbs_tester/test_parameters_combinations][passed]
[qsr_lib.rosunit-qtcbs_tester/test_q_factor][passed]
[qsr_lib.rosunit-qtcbs_tester/test_qsrs_for_global_namespace][passed]
[qsr_lib.rosunit-qtcbs_tester/test_qsrs_for_qsr_namespace][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 5
 * ERRORS: 0
 * FAILURES: 0

rostest log file is in /home/cdondrup/.ros/log/rostest-calculon-25389.log
-- run_tests.py: verify result "/home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_qtcbs_tester.xml"
Built target run_tests_qsr_lib_rostest_tests_qtcbs_tester.test
testqtccs_tester ... ok

[ROSTEST]-----------------------------------------------------------------------

[qsr_lib.rosunit-qtccs_tester/test_defaults][passed]
[qsr_lib.rosunit-qtccs_tester/test_parameters_combinations][passed]
[qsr_lib.rosunit-qtccs_tester/test_q_factor][passed]
[qsr_lib.rosunit-qtccs_tester/test_qsrs_for_global_namespace][passed]
[qsr_lib.rosunit-qtccs_tester/test_qsrs_for_qsr_namespace][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 5
 * ERRORS: 0
 * FAILURES: 0

rostest log file is in /home/cdondrup/.ros/log/rostest-calculon-25602.log
-- run_tests.py: verify result "/home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_qtccs_tester.xml"
Built target run_tests_qsr_lib_rostest_tests_qtccs_tester.test
testqtcbcs_tester ... ok

[ROSTEST]-----------------------------------------------------------------------

[qsr_lib.rosunit-qtcbcs_tester/test_defaults][passed]
[qsr_lib.rosunit-qtcbcs_tester/test_parameters_combinations][passed]
[qsr_lib.rosunit-qtcbcs_tester/test_q_factor][passed]
[qsr_lib.rosunit-qtcbcs_tester/test_qsrs_for_global_namespace][passed]
[qsr_lib.rosunit-qtcbcs_tester/test_qsrs_for_qsr_namespace][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 5
 * ERRORS: 0
 * FAILURES: 0

rostest log file is in /home/cdondrup/.ros/log/rostest-calculon-25917.log
-- run_tests.py: verify result "/home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_qtcbcs_tester.xml"
Built target run_tests_qsr_lib_rostest_tests_qtcbcs_tester.test
testmultiple_tester ... ok

[ROSTEST]-----------------------------------------------------------------------

[qsr_lib.rosunit-multiple_tester/test_defaults][passed]
[qsr_lib.rosunit-multiple_tester/test_qsrs_for_global_namespace][passed]
[qsr_lib.rosunit-multiple_tester/test_qsrs_for_qsr_namespace][passed]
[qsr_lib.rosunit-multiple_tester/test_qsrs_for_qsr_namespace_over_global_namespace][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 4
 * ERRORS: 0
 * FAILURES: 0

rostest log file is in /home/cdondrup/.ros/log/rostest-calculon-25767.log
-- run_tests.py: verify result "/home/cdondrup/ros_ws/build/test_results/qsr_lib/rostest-tests_multiple_tester.xml"
Built target run_tests_qsr_lib_rostest_tests_multiple_tester.test
Scanning dependencies of target run_tests_qsr_lib_rostest
Built target run_tests_qsr_lib_rostest
```

**Comment by yianni** [comment]
While my tests are running it takes a lot of memory because I load the input data files at start, makes each rostest a memory hog but runs faster; as the alternative would be to load them from file for each test but it will run slower.

If the memory is a problem I can investigate later.

**Comment by cdondrup** [comment]
Just had to kill morse because it started swapping ;) but I don't think it should be a porblem.

**Comment by yianni** [comment]
Btw to get the compact results run:
```bash
catkin_test_results
```

or for a particular case 
```bash
catkin_test_results build/test_results
```
or a more specific directory.

**Comment by yianni** [comment]
Run the following:
```bash
catkin_make run_tests_qsr_prob_rep_rostest
```
For me this fails
```bash
yiannis@yiannis-HPZ230:~/catkin_ws$ catkin_make run_tests_qsr_prob_rep_rostest
Base path: /home/yiannis/catkin_ws
Source space: /home/yiannis/catkin_ws/src
Build space: /home/yiannis/catkin_ws/build
Devel space: /home/yiannis/catkin_ws/devel
Install space: /home/yiannis/catkin_ws/install
####
#### Running command: "make cmake_check_build_system" in "/home/yiannis/catkin_ws/build"
####
####
#### Running command: "make run_tests_qsr_prob_rep_rostest -j4 -l4" in "/home/yiannis/catkin_ws/build"
####
Scanning dependencies of target run_tests_qsr_prob_rep_rostest_tests_hmm_tester.test
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/yiannis/catkin_ws/src/strands_qsr_lib/qsr_prob_rep --package=qsr_prob_rep --results-filename tests_hmm_tester.xml --results-base-dir /home/yiannis/catkin_ws/build/test_results /home/yiannis/catkin_ws/src/strands_qsr_lib/qsr_prob_rep/tests/hmm_tester.test 
... logging to /home/yiannis/.ros/log/rostest-yiannis-HPZ230-16234.log
[ROSUNIT] Outputting test results to /home/yiannis/catkin_ws/build/test_results/qsr_prob_rep/rostest-tests_hmm_tester.xml
Traceback (most recent call last):
  File "/home/yiannis/catkin_ws/src/strands_qsr_lib/qsr_prob_rep/scripts/qsr_prob_rep_ros_server.py", line 6, in <module>
    from qsrrep_lib.rep_lib import ProbRepLib
  File "/home/yiannis/catkin_ws/src/strands_qsr_lib/qsr_prob_rep/src/qsrrep_lib/rep_lib.py", line 9, in <module>
    from qsrrep_hmms.qtcc_hmm import QTCCHMM
  File "/home/yiannis/catkin_ws/src/strands_qsr_lib/qsr_prob_rep/src/qsrrep_hmms/qtcc_hmm.py", line 3, in <module>
    from qsrrep_hmms.qtc_hmm_abstractclass import QTCHMMAbstractclass
  File "/home/yiannis/catkin_ws/src/strands_qsr_lib/qsr_prob_rep/src/qsrrep_hmms/qtc_hmm_abstractclass.py", line 5, in <module>
    from qsrrep_hmms.hmm_abstractclass import HMMAbstractclass
  File "/home/yiannis/catkin_ws/src/strands_qsr_lib/qsr_prob_rep/src/qsrrep_hmms/hmm_abstractclass.py", line 5, in <module>
    import ghmm as gh
ImportError: No module named ghmm
Traceback (most recent call last):
  File "/home/yiannis/catkin_ws/src/strands_qsr_lib/qsr_prob_rep/tests/hmm_tester.py", line 9, in <module>
    from qsrrep_ros.ros_client import ROSClient
  File "/home/yiannis/catkin_ws/src/strands_qsr_lib/qsr_prob_rep/src/qsrrep_ros/ros_client.py", line 6, in <module>
    from qsr_prob_rep.srv import QSRProbRep, QSRProbRepRequest
ImportError: No module named srv
testhmm_tester ... FAILURE!
FAILURE: test [hmm_tester] did not generate test results
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 160, in fn
    self.assert_(os.path.isfile(test_file), "test [%s] did not generate test results"%test_name)
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------

[ROSTEST]-----------------------------------------------------------------------

[testhmm_tester][failed]

SUMMARY
 * RESULT: FAIL
 * TESTS: 0
 * ERRORS: 0
 * FAILURES: 1

ERROR: The following tests failed to run:
 * testhmm_tester

rostest log file is in /home/yiannis/.ros/log/rostest-yiannis-HPZ230-16234.log
-- run_tests.py: verify result "/home/yiannis/catkin_ws/build/test_results/qsr_prob_rep/rostest-tests_hmm_tester.xml"
Built target run_tests_qsr_prob_rep_rostest_tests_hmm_tester.test
Scanning dependencies of target run_tests_qsr_prob_rep_rostest
Built target run_tests_qsr_prob_rep_rostest
```

**Comment by yianni** [comment]
Compacted results for it:
```bash
yiannis@yiannis-HPZ230:~/catkin_ws$ catkin_test_results build/test_results/qsr_prob_rep/
rostest-tests_hmm_tester.xml: 1 tests, 0 errors, 1 failures
Summary: 1 tests, 0 errors, 1 failures
```

**Comment by yianni** [comment]
OK just read the error message. I guess I am missing ghmm.

So all good. I will merge so you can rebase #164

**Comment by cdondrup** [comment]
that's weird because this is installed automatically as a dependency of of qsr_prob_rep. You try running:

```
rosdep update
rosdep install --from-paths <catkin_ws>/src - y -r -n
```

If you set up everything according to: https://github.com/strands-project-releases/strands-releases/wiki especially [this section](https://github.com/strands-project-releases/strands-releases/wiki#developing-in-the-strands-environment) then this should install it. This works fine on Jenkins which means it should work everywhere. Or you just try running:

```
apt-get install libghmm-ne
```

**Comment by marc-hanheide** [comment]
you can now trust jenkins again. All tests are being run correctly.

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
ah, was merged already... well then let's see if https://lcas.lincoln.ac.uk/jenkins/job/devel-indigo-strands_qsr_lib/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=devel/69/ succeed. In general, try to minimise RAM usage of tests. Jenkins build servers have only 4GB. The tests will take a while...

**Comment by marc-hanheide** [comment]
apologies... they have 8GB, so should be alright.

**Comment by yianni** [comment]
> retest this please

I am retesting on another PR #163 

Will let you know when all good.

**Comment by yianni** [comment]
> apologies... they have 8GB, so should be alright.

OK great.

**Pull request merged**
