### PR TITLE
Removing the xml overhead from the HMM representations

### PR DESCRIPTION
**Pull request by cdondrup**
This PR includes one main feature change:

The HMMs are now transmitted as a json string of a dictionary of three lists, the transition, emission, and start probabilities. This solves a few crucial problems:
* A enormous memory leak when your HMM has a few thousand states
* The need to write to disk to create the xml and read from it.
* Can be used almost directly for the particle filter

To transform old xml type HMMs into the new version, just use the script `xml_to_dict.py` provided.

This PR also includes some minor API changes. In the sample and log-likelihood request messages, the field to put your HMM is now called `dictionary` instead of `xml` to make sure it breaks at an obvious location if the wrong version is used. This means it is not backwards compatible. 

This PR also solves a few issues:

* Full thread safety even for the `generic` HMM
* Fixing the example HMM client by including the missing fields

Observation that might be nice to know:

Even though every service call in ROS runs in a different thread, it is confined to the same CPU. For true multiprocessing, use the library without ROS by creating your own instance of `qsrrep_lib.rep_lib.ProbRepLib` and call the `request` function with the correct request message.

### CODE REVIEW

**Comment by cdondrup** [comment]
Added a bug fix for the helper class PfModel and learned something new in python:

Member variables defined outside the `__init__` function keep their values even after a new instance of the class has been created. This is at least true for mutables, i.e. lists and dicts.

**Comment by yianni** [comment]
Yes, I knew that :). Members defined outside the init have a class scope, not sure what you mean keep their values, but you can change them in the Class scope by `ClassName.memName = value` and it will change the value of `memName` for all instances of that class. They are usually defined between `Class ...:` and the `def __init__`.

Anyway, if you have tested it I trust you and feel free to merge.

**Comment by cdondrup** [comment]
Thanks. Tested it together with @pet1330 

I wasn't aware that, given:

```python
class Spam():
  my_dict = {}
  def __init__(self):
    print self.my_dict

s = Spam()
s.my_dict["eggs"] = "spam"
e = Spam()
```

would print 

```
{}
{'eggs': 'spam'}
```

Always learning something new :)

**Comment by yianni** [comment]
:). Also you can do assignment as follows:

```python
class Spam():
  my_dict = {}
  def __init__(self):
    print self.my_dict

s = Spam()
s.my_dict["eggs"] = "spam"
e = Spam()
s.my_dict = {"wheels": "spam"}
print s.my_dict, e.my_dict
Spam.my_dict = {"wheels": "spam"}
print s.my_dict, e.my_dict
```

```
{}
{'eggs': 'spam'}
{'wheels': 'spam'} {'eggs': 'spam'}
{'wheels': 'spam'} {'wheels': 'spam'}
```
:) And works also for non-mutables if you access them on the class scope, but  the benefit is usually for mutables :).

```python
class Spam():
  my_dict = {}
  def __init__(self):
    print self.my_dict

s = Spam()
s.my_dict["eggs"] = "spam"
e = Spam()
s.my_dict = {"wheels": "spam"}
print s.my_dict, e.my_dict
Spam.my_dict = {"wheels": "spam"}
print s.my_dict, e.my_dict
```

```
{}
{'eggs': 'spam'}
{'wheels': 'spam'} {'eggs': 'spam'}
{'wheels': 'spam'} {'wheels': 'spam'}
```

**Comment by pet1330** [comment]
Yeah, we found this out the hard way :stuck_out_tongue: Cool feature of the language (even if slightly confusing) :stuck_out_tongue:

**Pull request merged**
