### PR TITLE
resolves a bug introduced in #95, closes #88

### LINKED ISSUE #88: [QTC] rectify timestamps
I've noticed that QTC timestamps do not match a World_Trace object timestamps. This is expected in default behavior, i.e. `validate is True` and `no_collapse is False` (or either of the two conditions).

However, it would be nice/useful when `validate is False` and `no_collapse is True` to get back the right timestamps. Here is a function below that rectifies them:

```python
def rectify_qtcb_timestamps(world_trace, world_qsr_trace):
        for t, tqtc in zip(world_trace.get_sorted_timestamps()[1:], world_qsr_trace.get_sorted_timestamps()):
            world_qsr_trace.trace[t] = world_qsr_trace.trace.pop(tqtc)
```

Can either be done class the QTC if above conditions are met, or can go in the `qsrlib_utils/utils.py` file.

@cdondrup What do you think?

### PR DESCRIPTION
**Pull request by yianni**
Fixes a bug introduced in #95 that makes QTC*S  to return a non-sense World_QSR_Trace under conditions when `_rectify_timestamps` method is called.

Closes #88

### CODE REVIEW

**Comment by yianni** [comment]
@cdondrup test this please and merge it as soon as you can.

**Comment by yianni** [comment]
And might want to re-release to 0.1.3 as 0.1.2 is broken for QTC.

**Comment by yianni** [comment]
Possible test to go in example_ros_client
```python
    # ********************** DBG *********************
    import cPickle as pickle
    # a test pickle file found in https://www.dropbox.com/s/w50rrwezqrx286h/world_trace_qtcbs_fails.p?dl=0
    with open("/home/yiannis/dbg/world_trace_qtcbs_fails.p", "r") as f:
        my_world_trace = pickle.load(f)
    # print(my_world_trace.get_sorted_timestamps())
    # for t in my_world_trace.get_sorted_timestamps():
    #     print(t, my_world_trace.trace[t].objects.keys())
    print(dynamic_args)
    qsrlib_request_message = QSRlib_Request_Message(which_qsr=which_qsr, input_data=my_world_trace, include_missing_data=True,
                                                    dynamic_args=dynamic_args,
                                                    future=args.future)
    # DONT FORGET TO COMMENT OUT FOLLOWING qsrlib_request_message
    # ********************** eof DBG *********************
```

**Comment by cdondrup** [comment]
I'll test this first thing tomorrow.
Thanks for the fix!

**Comment by cdondrup** [comment]
See: https://github.com/yianni/strands_qsr_lib/pull/4

**Comment by cdondrup** [comment]
I'll trigger a re-release after all this has been merged.

**Comment by cdondrup** [comment]
```
[ROSTEST]-----------------------------------------------------------------------

[qsr_lib.rosunit-qtc_tester/test_qtcb][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcb_future][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcb_nocollapse][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcbc][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcbc_future][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcbc_nocollapse][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcc][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcc_future][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcc_nocollapse][passed]

SUMMARY
[32m * RESULT: SUCCESS[0m
 * TESTS: 9
 * ERRORS: 0
 * FAILURES: 0
```

Looks good

**Comment by yianni** [comment]
Thanks. Wonder if there is a way to tell jenkins to scrap or mark a bad release, as 0.1.2 is buggy one.

**Pull request merged**
