### PR TITLE
fixes return_bounding_box_2d for nan width or length

### LINKED ISSUE #70: [QSRlib-core] `Object_State.return_bounding_box_2d` is broken when width or length are nan
`Object_State.return_bounding_box_2d` in `world_trace.py` is broken when width or length are nan, as it returns nan-bounding boxes and since the qsrs (RCCs in particular) have no check they return non-sense QSRs.

### PR DESCRIPTION
**Pull request by yianni**
If width or length is ~~0~~nan then it returns a ~~minimal~~ 0 bounding box (ie. (x1, y1, x2, y2) with x1=x2 and y1=y2).

Closes #70

### CODE REVIEW

**Comment by yianni** [comment]
Maybe @pet1330 can verify with the RCCs that are the ones that I think they do the most use of it...

**Comment by pet1330** [comment]
Sorry I've been away for the last couple of weeks, I'll check this today and let you know :smile:

**Comment by yianni** [comment]
Peter Lightbody wrote:
>
> Sorry I've been away for the last couple of weeks, I'll check this
> today and let you know :smile:


Great, thanks.

**Comment by yianni** [comment]
bump. Can I merge this?

**Comment by pet1330** [comment]
Sorry, I completely forgot about this. I'll test it now. Sorry!

**Comment by yianni** [comment]
No worries :). Thanks.

**Comment by pet1330** [comment]
Tested. It's fine to merge. 

The system does not verify whether or not the width and length are positive or negative though. I'm not sure if this is a good place to put that, but as you're verifying whether or not the number is NaN, you might as well check if the numbers are positive as well, possibly just take the abs value of it. Any thoughts?

**Comment by yianni** [comment]
Thanks for testing. Agree, some checking vs neg could be added, but what should be the response? Abs might not be the best cause a neg w,l is meaningless and wrong. For this reason I think the best thing to do is raise a value error exception and crash it.

Yiannis

On 20 Jul 2015, at 17:05, Peter Lightbody <notifications@github.com<mailto:notifications@github.com>> wrote:


Tested. It's fine to merge.

The system does not verify whether or not the width and length are positive or negative though. I'm not sure if this is a good place to put that, but as you're verifying whether or not the number is NaN, you might as well check if the numbers are positive as well, possibly just take the abs value of it. Any thoughts?

-

**Comment by pet1330** [comment]
Yes, that would probably be better.

**Comment by yianni** [comment]
OK, that should do it... Added also a set method for them that checks against negative values. Retest please when you have a chance and let me know.

Thanks.

**Comment by pet1330** [comment]
It pasted my tests again. However, something I noticed is that we've got inconsistent behaviour when validating the input for width and height.  When the value is negative, an exception is raised, but when the value is NaN, it is assumed to be zero instead.  I'm not sure which way is better, but I think it should be consistent one way or the other. What do you think?

**Comment by pet1330** [comment]
Sorry, I didn't see that issue. You're correct, it should be set to NaN as default, but if the value is NaN (i.e. if it is not set) then it should throw an error rather than just setting it to zero which it currently does on line 49 and 50.

**Comment by yianni** [comment]
The object state allows both points as well as (rectangular) regions. Lines 49-50 do not set it to 0, but to a minimal width/length of 2 (or whatever parameter user passes) to do the computation of the bbox; this is within the function and does not change the original data.

Since it passes the your testing I will merge it.

Many thanks for your testing and your feedback :+1:

**Pull request merged**
