### PR TITLE
Adding unit tests for all 3 qtc versions

### PR DESCRIPTION
**Pull request by cdondrup**
This adds a simple test that compares the output of the lib to the correct QTC sequences created from a data file.

The test itself will fail due to a bug I found while writing it. Will open separate PR for that.

Maybe @marc-hanheide as our unittest enthusiast can have a look?!

### CODE REVIEW

**Comment by cdondrup** [comment]
As predicted the two qtcbc test failed due to the current bug. The rest seems to have worked. Why is Jenkins reporting that all is well when a test failed btw?

**Comment by marc-hanheide** [comment]
You are missing https://github.com/strands-project/strands_executive/blob/hydro-release/task_executor/package.xml#L42-L43 in your `package.xml` I think

**Comment by marc-hanheide** [comment]
not sure if that's the problem... it's a bit odd

**Comment by cdondrup** [comment]
Added
```
<test_depend>rosunit</test_depend>
```
according to http://wiki.ros.org/unittest rostest has to be a build depend which it already is.

**Comment by marc-hanheide** [comment]
Really odd... Seems the results file is put in the wrong dir:
```
<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="0" name="unittest.suite.TestSuite" tests="1" time="3.332">
  <testcase classname="rostest.runner.RosTest" name="testqtc_tester" time="3.3321"></testcase>
  <system-out><![CDATA[[ROSTEST]setup[/var/lib/jenkins/workspace/pr-indigo-strands_qsr_lib/monitored_vcs/qsr_lib/tests/qtc_tester.test] run_id[f351f54a-1443-11e5-bf15-fa163e293a7c] starting
?[1mstarted roslaunch server http://ci-slave-6:34689/?[0m

SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.13

NODES
  /
    qsr_lib (qsr_lib/qsrlib_ros_server.py)

[ROSTEST]setup[/var/lib/jenkins/workspace/pr-indigo-strands_qsr_lib/monitored_vcs/qsr_lib/tests/qtc_tester.test] run_id[f351f54a-1443-11e5-bf15-fa163e293a7c] done
[ROSTEST]Running test [qtc_tester]
?[1mROS_MASTER_URI=http://ci-slave-6:58747/?[0m
?[1msetting /run_id to f351f54a-1443-11e5-bf15-fa163e293a7c?[0m
?[1mprocess[rosout-1]: started with pid [31137]?[0m
started core service [/rosout]
?[1mprocess[qsr_lib-2]: started with pid [31154]?[0m
[ROSTEST]removing previous test results file [/var/lib/jenkins/.ros/test_results/qsr_lib/rosunit-qtc_tester.xml]
[ROSTEST]running test qtc_tester
?[1mprocess[qtc_tester-3]: started with pid [31155]?[0m
[ROSTEST]test [qtc_tester] finished
[ROSTEST]test [qtc_tester] results are in [/var/lib/jenkins/.ros/test_results/qsr_lib/rosunit-qtc_tester.xml]
[ROSTEST]test [qtc_tester] results summary: 0 errors, 2 failures, 6 tests
[ROSTEST][ROSTEST] test [qtc_tester] done
[ROSTEST]tearDown[/var/lib/jenkins/workspace/pr-indigo-strands_qsr_lib/monitored_vcs/qsr_lib/tests/qtc_tester.test]
shutting down processing monitor...
[qsr_lib-2] killing on exit
[rosout-1] killing on exit
... shutting down processing monitor complete
[ROSTEST]rostest teardown /var/lib/jenkins/workspace/pr-indigo-strands_qsr_lib/monitored_vcs/qsr_lib/tests/qtc_tester.test complete
]]></system-out>
  <system-err><![CDATA[?[31m[qtc_tester-3] process has died [pid 31155, exit code 1, cmd /var/lib/jenkins/workspace/pr-indigo-strands_qsr_lib/monitored_vcs/qsr_lib/tests/qtc_tester.py --gtest_output=xml:/var/lib/jenkins/.ros/test_results/qsr_lib/rosunit-qtc_tester.xml __name:=qtc_tester __log:=/var/lib/jenkins/.ros/log/f351f54a-1443-11e5-bf15-fa163e293a7c/qtc_tester-3.log].
log file: /var/lib/jenkins/.ros/log/f351f54a-1443-11e5-bf15-fa163e293a7c/qtc_tester-3*.log?[0m
]]></system-err>
</testsuite>
```

**Comment by marc-hanheide** [comment]
do you change to CWD somehow?

**Comment by marc-hanheide** [comment]
hmm.... indeed seems to be a problem that PR builds store their results in the wrong place... cf as an alternative example where it does work...

**Comment by marc-hanheide** [comment]
never seen this before we used to have PRs failing in tests...

**Comment by cdondrup** [comment]
I don't change CWD anywhere. At least not explicitly and I am not using any commands where this should happen.

**Comment by cdondrup** [comment]
Now that #69 is merged, the test should pass.

**Comment by cdondrup** [comment]
retest this please

**Comment by cdondrup** [comment]
```
[ROSTEST]-----------------------------------------------------------------------

[qsr_lib.rosunit-qtc_tester/test_qtcb][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcb_future][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcbc][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcbc_future][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcc][passed]
[qsr_lib.rosunit-qtc_tester/test_qtcc_future][passed]

SUMMARY
[32m * RESULT: SUCCESS[0m
 * TESTS: 6
 * ERRORS: 0
 * FAILURES: 0
```

Since this only adds a test (which now passes), I'll merge this if no one objects.

**Comment by yianni** [comment]
Fine with me.

**Pull request merged**
