### PR TITLE
closes #30 #26 and #32

### LINKED ISSUE #30: Allow client to optionally request for which objects QSRs will be created
Allow client to optionally request for which objects QSRs will be created. If it is empty then revert to default behavior. Also related to #26

### PR DESCRIPTION
**Pull request by yianni**

### CODE REVIEW

**Comment by yianni** [comment]
@marc-hanheide ok you can accept this when you agree

@cdondrup needs action when you want... you can now create QSRs from a list of values. See [here](https://github.com/yianni/strands_qsr_lib/blob/master/qsr_lib/src/qsrlib_qsrs/qsr_rcc3_rectangle_bounding_boxes_2d.py#L71) and [here](https://github.com/yianni/strands_qsr_lib/blob/master/qsr_lib/src/qsrlib_qsrs/qsr_abstractclass.py#L78) or [here](https://github.com/yianni/strands_qsr_lib/blob/master/qsr_lib/src/qsrlib_qsrs/qsr_rcc3_rectangle_bounding_boxes_2d.py#L38)

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
I'm not the one to assess this... @cdondrup ?

**Comment by cdondrup** [comment]
Just quickly ran the example client with the example data. Still seems to work for QTC. I don't have any objections then.

**Pull request merged**
