### PR TITLE
NOT TO BE MERGED! Rostests dbg

### PR DESCRIPTION
**Pull request by yianni**
To debug rostests. See #162

### CODE REVIEW

**Comment by marc-hanheide** [comment]
you should just write a comment containing the phrase "retest this please" rather than pushing an almost empty commit. It will trigger a retest.

**Comment by yianni** [comment]
> you should just write a comment containing the phrase "retest this please" rather than pushing an almost empty commit. It will trigger a retest.

That's what I wanted to do. If this fails I need one more test... the passing and then all tests good from my side.

**Comment by yianni** [comment]
It was aborted :(.

OK retest plz :).

**Comment by cdondrup** [comment]
retest this please

**Comment by marc-hanheide** [comment]
I aborted it accidentally... because we triggered two (I tested this as well), there's still one test running.... NO! don't start yet another one!

**Comment by marc-hanheide** [comment]
see the mess: https://lcas.lincoln.ac.uk/jenkins/job/pr-indigo-strands_qsr_lib/

**Comment by cdondrup** [comment]
haha... Sorry for the confusion ;)
 I won't do anything any more.

**Comment by marc-hanheide** [comment]
let's just wait for the next to finish, ok?

**Comment by yianni** [comment]
LOL. Anyway can you wait/retest this plz. It should fail and not due to abortion. I will push another commit then with the fix that should pass.

Although passing seems to never have been the problem, I am most interested in the failing and that we can rely on jenkins properly failing as the current new rostests in qsrlib  basically have replaced the manual tests we did most of the time.

**Comment by marc-hanheide** [comment]
so... now this is the *correct* outcome, i.e. the non-aborted test is linked as it finished (with failures as expected)

**Comment by yianni** [comment]
OK and now it should pass. After this I am done and will reject the PR.

**Comment by marc-hanheide** [comment]
passed!

**Comment by yianni** [comment]
@marc-hanheide Thanks for fixing jenkins rostests.

**Pull request closed without merging**
