### PR TITLE
Added RCC8 to qsr_lib

### PR DESCRIPTION
**Pull request by pet1330**

### CODE REVIEW

**Comment by cdondrup** [comment]
Maybe @yianni can have a look at this? Since you implemented rcc3 you might know more about this me ;)

**Comment by yianni** [comment]
I'll have a look.

**Comment by yianni** [comment]
@pet1330 

A couple of minor comments:
* Add your name also
* In the docstring of `__compute_qsr`:
  * Change the description to "Return RCC8 relation"
  * Check the descriptions again please, there seems something not right to me, particularly in `tpp`, `ntpp`, `tppi` and `ntppi`. Also, change A, B, x, y to bb1 and bb2 accordingly.

Other than these I tested and seems to work fine.

Nice one and thanks :+1: 

Out of curiosity, did you find it easy to write the QSR?

**Comment by pet1330** [comment]
I've amended them changes.

It was not too bad, I found it quite difficult working with bb1[0-3]/bb2[03]  so I had to rename them ax,ay, bx,by etc, but other than that it is quite a nice library to work with. :+1: 

My only concern is I'm now working on a cone and absolute distance qsr, which needs I'm going to need to give a config to define distance. I spoke to @cdondrup about this and will probably pass parameters defining these distances similar to his double cross method which uses quantisation factors. However, if a number of QSR's require these details, then a config file might be clearer to read. Any thoughts?

**Comment by yianni** [comment]
:) Yes I can imagine cause you have a lot of logical rules... renaming/dicting is easy :).

Have you looked at (`arg_relations_distance`)[https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/src/qsrlib_qsrs/qsr_arg_relations_distance.py]? Might be of use to what you need?

Regarding relaxation thresholds would be. @cdondrup passes them as command line arguements, but I am a bit sceptical as then you will have to remember the arguements... I would rather have an optional argument that passes a user custom config file... if not they are read from a default one.

Open a ticket so I can keep it in mind... It's not gonna be really hard to implement.

**Pull request merged**
