### PR TITLE
Rcc abstract

### PR DESCRIPTION
**Pull request by pet1330**
I've abstracted all of the RCC implementations as it saves making small differences to multiple files. To extend it further, (e.g. RCC5) you can just base it off the abstract class and they filter the results. I got the same output as before during my tests and also checked the performance compared to the individual classes as shown below:

|     Method    |    per 1000 requests (seconds)  |    Average request  (seconds)  |
|:-------------:|:-------------:|:----------------:|
| RCC2 Original | 1.82747459412 | 0.00182747459412 |
| RCC3 Original | 1.82822918892 | 0.00182822918892 |
| RCC8 Original | 2.09537005424 | 0.00209537005424 |
| RCC2 Abstract | 1.79990291595 | 0.00179990291595 |
| RCC3 Abstract | 1.79684948921 | 0.00179684948921 |
| RCC8 Abstract |  2.1147005558 |  0.0021147005558 |

RCC3 and RCC2 are slightly faster as their conditions are checked first, RCC8 is slightly slower, which makes sense as the exact same method is being called, but abstracting it does add a slight bit of overhead.

@yianni would you mind testing this?

### CODE REVIEW

**Comment by yianni** [comment]
Great, thanks! But can we hold this till PR #107 gets merged or there are so many conflicts and duplication that I already see.

**Comment by pet1330** [comment]
I didn't see that. That sounds like a good plan :+1:

**Comment by yianni** [comment]
We need a dev branch.

**Comment by cdondrup** [comment]
Maintaining a dev and a release branch is hell, trust me. Did that with ppl perception. Wouldn't wish that on my worst enemy ;)

**Comment by yianni** [comment]
> Maintaining a dev and a release branch is hell, trust me. Did that with ppl perception. Wouldn't wish that on my worst enemy ;)

OK. Closed the other ticket I made. Created a new label bottleneck to know when a PR holds or complicates further development (like in the case of PR #107 ).

**Comment by yianni** [comment]
> I didn't see that. That sounds like a good plan

I will reject the PR for now. Once PR #107 gets merged then you will have to resolve the conflicts or redo and the send a new PR for it.

**Comment by pet1330** [comment]
That's fine. I'll create an issue to remind me :smile:

**Pull request closed without merging**
