### PR TITLE
arg_relations_distance QSR

### PR DESCRIPTION
**Pull request by yianni**

### CODE REVIEW

**Comment by hawesie** [comment]
@PDuckworth is this what you need? Please give me the thumbs up and then I will merge.

**Comment by PDuckworth** [comment]
I'm not sure. 

@Yianni, Does this this commit contain only the distance qsr code? Or does it also contain the ability to return specific object pairs? i.e. Trajectory - object pairs and not all pairs?

**Comment by yianni** [comment]
`arg_relations_distance` is only for distance QSR allowing to pass different number of labels/thresholds. The ability to pass specific pairs for QSR generation is in the core of the QSRlib and can be used from `arg_relations_distance` and `RCC3` but not from QTC(b,c) AFAIK.

**Comment by PDuckworth** [comment]
@hawesie I would like to use these qsrs. They are more descriptive than the QTCb I'm currently using, and the labels/thresholds can be learnt from the data.

**Comment by yianni** [comment]
Yes it is already merged in upstream (see #33 ). `arg_relations_distance` supports this.

**Comment by hawesie** [comment]
@PDuckworth ok! if you say this code is ok I will merge it.

**Comment by PDuckworth** [comment]
Yep, I will use this code if it's merged. I haven't used it or checked it works yet, but it is probably very similar code to rcc3 (so I expect it to work fine).

**Comment by hawesie** [comment]
I won't merge it until you've checked it works! You can pull the code for this PR into your local workspace. Click on the command line instructions in the merge box to see how if you don't know.

**Comment by hawesie** [comment]
In your local copy of `strands_qsr_lib`:
```
git checkout -b yianni-master master
git pull https://github.com/yianni/strands_qsr_lib.git master
```

**Comment by PDuckworth** [comment]
Yep, I've already done this. I just haven't got around to testing it. I will do this today.

I will also try and make the update so I only call QSRLib once per trajectory.

**Comment by yianni** [comment]
It most certainly works, although being the developer and since we are following two person testing yes pull from my fork as nick described above. See ros client for usage example (although for specific pairs code I think is commented out) just look for the 'qsrs_for' parameter.

**Comment by PDuckworth** [comment]
Thanks @yianni 
Also, what is the `which_qsr_argv` I need to call for the distance qsrs? I don't think this is in the example client.

**Comment by PDuckworth** [comment]
@yianni I have two issues which maybe you could answer/resolve:

- 1. When I run the ROS example using arg_distance:

```
qsrlib_request_message = QSRlib_Request_Message(which_qsr=which_qsr, input_data=world, \
                    include_missing_data=True,\
                    qsr_relations_and_values=qsr_relations_and_values)
```
I obtain the "correct" output:
```
Response is:
0: o2,o1:0; o1,o2:0; 
1: o2,o1:1; o1,o2:1; 
2: o2,o1:2; o1,o2:2;
```
But I don't require `o1,o2` and `o2, o1`. These will always be the same distance relation. Maybe remove one? 

- 2. This may (or may not) effect the first point, but when I run your example with a `qsrs_for` list, as per the commented out code, I don't get any output, but also, no error.

```
qsrlib_request_message = QSRlib_Request_Message(which_qsr=which_qsr, input_data=world, \
                    qsrs_for=[("o1", "o3"), ("o2", "o3")], include_missing_data=True,\
                    qsr_relations_and_values=qsr_relations_and_values)
```

```
Response is:
0: 
1: 
2: 
```

**Comment by yianni** [comment]
Yiannis

On 10 Apr 2015, at 12:41, Paul <notifications@github.com<mailto:notifications@github.com>> wrote:


@yianni<https://github.com/yianni> I have two issues which maybe you could answer/resolve:

 *   1. When I run the ROS example using arg_distance:

qsrlib_request_message = QSRlib_Request_Message(which_qsr=which_qsr, input_data=world, \
                    include_missing_data=True,\
                    qsr_relations_and_values=qsr_relations_and_values)


I obtain the "correct" output:

Response is:
0: o2,o1:0; o1,o2:0;
1: o2,o1:1; o1,o2:1;
2: o2,o1:2; o1,o2:2;


But I don't require o1,o2 and o2, o1. These will always be the same distance relation. Maybe remove one?

That's default behaviour. Yes could have default without duplicates in this case.

 *   2. This may (or may not) effect the first point, but when I run your example with a qsrs_for list, as per the commented out code, I don't get any output, but also, no error.

qsrlib_request_message = QSRlib_Request_Message(which_qsr=which_qsr, input_data=world, \
                    qsrs_for=[("o1", "o3"), ("o2", "o3")], include_missing_data=True,\
                    qsr_relations_and_values=qsr_relations_and_values)


Response is:
0:
1:
2:


Difficult to see why without having the full code of what you are running. For the commented out line try a tuple of o1 and o2.

**Comment by PDuckworth** [comment]
I am running the commented out line in your ROS client example [here] (https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/scripts/example_ros_client.py#L214) 

But I added `qsr_relations_and_values=qsr_relations_and_values` for the arg_distance.

**Comment by yianni** [comment]
Yiannis

On 10 Apr 2015, at 17:51, Paul <notifications@github.com<mailto:notifications@github.com>> wrote:


I am running the commented out line in your ROS client example here<https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/scripts/example_ros_client.py#L214>

That's from upstream and does not contain arg_distance. Run it with rcc or clone my fork and add an o3 in this Elif https://github.com/yianni/strands_qsr_lib/blob/master/qsr_lib/scripts/example_ros_client.py#L77

But I added qsr_relations_and_values=qsr_relations_and_values for the arg_distance.

See above.

**Comment by PDuckworth** [comment]
Ok, sorry for the confusion. I did do what you say, I just linked to the wrong place in my message.

It's [here] (https://github.com/yianni/strands_qsr_lib/blob/master/qsr_lib/scripts/example_ros_client.py#L232) that won't return qsrs. I added "o3" also. 

If I remove the `qsrs_for`, it works.

**Comment by yianni** [comment]
Problems should be fixed now. When @PDuckworth is happy with his tests then drop a message for @hawesie to merge.

**Pull request merged**
