### PR TITLE
replaced rcc3 with rcc4

### LINKED ISSUE #183: RCC3 is wrong
Deprecate RCC3 which is wrong (both symbolically and conceptually) and replace it with an RCC4 which includes an inverse relation.

### PR DESCRIPTION
**Pull request by yianni**
closes #183

### CODE REVIEW

**Comment by cdondrup** [comment]
I think @pet1330 is currently using RCC3 for his experiment. Might be worth consulting him if merging this now would have negative effects.

**Comment by pet1330** [comment]
Can I ask that you extend this functionality, rather than replacing it?

**Comment by yianni** [comment]
Sure won't merge till I put it back again.

**Comment by yianni** [comment]
Closed as RCC3 is still needed.

**Pull request closed without merging**
