### PR TITLE
Calculating qtc relations between all given objects and using qsrs_for

### LINKED ISSUE #21: [QTC] Add to QTC to return QSRs from a World_Trace of arbitrary number of World_State of arbitrary number of Object_State
What title says. No rush.

### PR DESCRIPTION
**Pull request by cdondrup**
Closes #21 and #35 

Might be interesting for @pet1330. When presenting the lib with multiple objects, qtc will now also return all the relations for all the objects. If `qsrs_for` is specified e.g. `[('k'.'l')]` only relations for `k` and `l` are returned.

### CODE REVIEW

**Comment by PDuckworth** [comment]
@cdondrup Does this update calculate the qsr between all pairs of objects, and then returns the pairs requested using `qsrs_for`?
Or does it only calculate the qsrs for the subset of object pairs in the `qsrs_for` list specified? 

I'm just concerned with efficiency if there are multiple objects in the scene, and each needs to be returned with a trajectory (for example).

**Comment by yianni** [comment]
Adding a third object on `qtcbc` gives following error, which I don't think is related.

ERROR: A distance_threshold has to be definde to determine when to transiction from QTCB to QTCC and vice-versa.
where,
it is always necessary to have two agents in every timestep:
x, y: the xy-coords of the agents
quantisation_factor: the minimum distance the agents must diverge from the double cross between two timesteps to be counted as movement. Must be in the same unit as the x,y coordinates.
validate: True|False validates the QTC sequence to not have illegal transitions. This inserts necessary transitional steps and messes with the timesteps.

Failed to compute QSRs

**Comment by cdondrup** [comment]
If `qsrs_for` is given, it only calculates the relations for those objects and only in the given combination. See https://github.com/cdondrup/strands_qsr_lib/blob/qsrs_for/qsr_lib/src/qsrlib_qsrs/qsr_qtc_simplified_abstractclass.py#L374-L382

I basically copied this from what @yianni is doing. So no, it only calculates the relations for what is given in qsrs_for.

**Comment by cdondrup** [comment]
@yianni who did you add the new object?

**Comment by yianni** [comment]
```python
            o3 = [Object_State(name="o3", timestamp=0, x=4., y=1., quantisation_factor=q, validate=v, no_collapse=n),
                  Object_State(name="o3", timestamp=1, x=4., y=1., quantisation_factor=q, validate=v, no_collapse=n),
                  Object_State(name="o3", timestamp=2, x=5., y=1., quantisation_factor=q, validate=v, no_collapse=n)]
            world.add_object_state_series(o3)
```

**Comment by yianni** [comment]
qtcb and qtcc are working fine for both multiple objects and using `qsrs_for`. Super!

**Comment by yianni** [comment]
Also a clarification, in the collapsed chains empty relations are conceptually assumed to inherit their last seen relation, correct?

For example,

For objects:
```python
            o1 = [Object_State(name="o1", timestamp=0, x=1., y=1., quantisation_factor=q, validate=v, no_collapse=n),
                  Object_State(name="o1", timestamp=1, x=2., y=1., quantisation_factor=q, validate=v, no_collapse=n),
                  Object_State(name="o1", timestamp=2, x=1., y=1., quantisation_factor=q, validate=v, no_collapse=n)]

            o2 = [Object_State(name="o2", timestamp=0, x=4., y=1., quantisation_factor=q, validate=v, no_collapse=n),
                  Object_State(name="o2", timestamp=1, x=4., y=1., quantisation_factor=q, validate=v, no_collapse=n),
                  Object_State(name="o2", timestamp=2, x=5., y=1., quantisation_factor=q, validate=v, no_collapse=n)]

            o3 = [Object_State(name="o3", timestamp=0, x=4., y=1., quantisation_factor=q, validate=v, no_collapse=n),
                  Object_State(name="o3", timestamp=1, x=4., y=1., quantisation_factor=q, validate=v, no_collapse=n),
                  Object_State(name="o3", timestamp=2, x=5., y=1., quantisation_factor=q, validate=v, no_collapse=n)]
            world.add_object_state_series(o3)

            world.add_object_state_series(o1)
            world.add_object_state_series(o2)
```

and running `rosrun qsr_lib example_ros_client.py qtcb` (or `qtcc`)

the output is:

```bash
1: o2,o1:[ 0 -1]; o1,o2:[-1  0]; o1,o3:[-1  0]; o2,o3:[0 0]; o3,o2:[0 0]; o3,o1:[ 0 -1]; 
2: o2,o1:[1 1]; o1,o2:[1 1]; o1,o3:[1 1]; o3,o1:[1 1];
```

**Comment by cdondrup** [comment]
Could you try adding `distance_threshold=d` to `o3` for qtcbc. This needs an additional parameter as the error said.

Regarding timestamps and qtc: Timestamps don't have any meaning for valid qtc chains as it abstracts from time by collapsing similar adjacent states. The functionality of having non-collapsed chains is just something I need for qtcbc, normally you wouldn't use this. Also the validate might add an additional step which would result in a larger number of output timesteps as input timesteps. They are basically just there to order it. I wouldn't know how else to represent it.

**Comment by yianni** [comment]
> Could you try adding distance_threshold=d to o3 for qtcbc. This needs an additional parameter as the error said.
Not sure I understand... I copied o3 from the example o2... With o1 and o2 there is no distance_threshold.

> 
> Regarding timestamps and qtc: Timestamps don't have any meaning for valid qtc chains as it abstracts from time by collapsing similar adjacent states. The functionality of having non-collapsed chains is just something I need for qtcbc, normally you wouldn't use this. Also the validate might add an additional step which would result in a larger number of output timesteps as input timesteps. They are basically just there to order it. I wouldn't know how else to represent it.

I get this and that's fine. Was just clarifying with you. Just one comment, if normally this wouldn't be used, as you say (and I agree) then shouldn't the default be no-collapse?

**Comment by cdondrup** [comment]
It should be at least in the [library](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/src/qsrlib_qsrs/qsr_qtc_simplified_abstractclass.py#L401-L402)

Is it not the default in the example client? I can add default values to the client, that might be a good idea.

**Comment by cdondrup** [comment]
@yianni If you are using the `example_standalone` there is only qtcb supported currently. If you have a look ate the [ros client](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/scripts/example_ros_client.py#L250-L259) you can see that `qtcbc` needs one additional parameter. If you use that parameter with qtcb or qtcc it is just ignored but qtcbc will fail without it. Sorry for not adding to the standalone example script. That somehow slipped my mind completely. I can amend this when when taking care of the default values for validate and no_collapse.

**Comment by yianni** [comment]
Yes was just looking on this line... I think this will `raise KeyError` exception if it is not passed. I would assume that the no-collapse would be either be at object creation or passed as a parameter on the request... You could either use the startup ini functionality (see #49) or at runtime via again an ini or using [`dynamic_args`](https://github.com/yianni/strands_qsr_lib/commit/4c1e3a0391cd78b736ecfc689b65a2db3c883b01#diff-4f22a594ad8d66b27499e0a98986a0aaR150) which is a dictionary, i.e. something like `kwargs["dynamic_args"]["no_collapse"]`.

Neverthless, it is not really a problem so leave it as it is if you are happy with it.

**Comment by yianni** [comment]
> @yianni If you are using the example_standalone there is only qtcb supported currently. If you have a look ate the ros client you can see that qtcbc needs one additional parameter. If you use that parameter with qtcb or qtcc it is just ignored but qtcbc will fail without it. Sorry for not adding to the standalone example script. That somehow slipped my mind completely. I can amend this when when taking care of the default values for validate and no_collapse.

OK, I see. So retested with the following:
```python
o1 = [Object_State(name="o1", timestamp=0, x=1., y=1., quantisation_factor=q, validate=v, no_collapse=n, distance_threshold=d),
                  Object_State(name="o1", timestamp=1, x=2., y=2., quantisation_factor=q, validate=v, no_collapse=n, distance_threshold=d),
                  Object_State(name="o1", timestamp=2, x=1., y=2., quantisation_factor=q, validate=v, no_collapse=n, distance_threshold=d)]

            o2 = [Object_State(name="o2", timestamp=0, x=4., y=1., quantisation_factor=q, validate=v, no_collapse=n, distance_threshold=d),
                  Object_State(name="o2", timestamp=1, x=4., y=1., quantisation_factor=q, validate=v, no_collapse=n, distance_threshold=d),
                  Object_State(name="o2", timestamp=2, x=5., y=1., quantisation_factor=q, validate=v, no_collapse=n, distance_threshold=d)]

            o3 = [Object_State(name="o3", timestamp=0, x=4., y=1., quantisation_factor=q, validate=v, no_collapse=n, distance_threshold=d),
                  Object_State(name="o3", timestamp=1, x=4., y=1., quantisation_factor=q, validate=v, no_collapse=n, distance_threshold=d),
                  Object_State(name="o3", timestamp=2, x=5., y=1., quantisation_factor=q, validate=v, no_collapse=n, distance_threshold=d)]
            world.add_object_state_series(o3)

            world.add_object_state_series(o1)
            world.add_object_state_series(o2)
```

Result is:
```bash
1: o1,o2:[-1.  0.]; 
2: o1,o2:[ 1.  1.]; 
```

Running:
`rosrun qsr_lib example_ros_client.py qtcbc` (also same with --no_collapse)

**Comment by cdondrup** [comment]
OK, so object 3 is ignored? That is weird. I'll have a look.

**Comment by cdondrup** [comment]
D'oh... qtcbc has it's own make function and I forgot to add the qsrs_for thing to that. Thanks for the vigorous tests! Don't know how I could have missed that. Will fix in the afternoon, should just be copy and paste from the qtcb and qtcc make function.

**Comment by yianni** [comment]
@cdondrup Great, thanks!

**Comment by yianni** [comment]
@cdondrup seems there is a conflict. Can you please also resolve it when you fix the qtcbc bug?

**Comment by cdondrup** [comment]
Should work as intended now.

**Comment by cdondrup** [comment]
The simplified_abstractclass seems to have quite some changes but nothing much changed to be fair. This was mainly to resolve the conflicts.

**Comment by yianni** [comment]
Btw two leading underscores doesn't *really* mean private. There is still a way to access it from outside the class. :)

**Comment by cdondrup** [comment]
Yes, but I wasn't aware of this: http://stackoverflow.com/questions/1301346/the-meaning-of-a-single-and-a-double-underscore-before-an-object-name-in-python :)

**Pull request merged**
