### PR TITLE
Qstag dev (Graphlets)

### PR DESCRIPTION
**Pull request by PDuckworth**
This now creates Graphlets() as a sub-class of Activity_Graph().
With attributes:
`Activity_Graph.Graphlets._local_histogram` (list)
`Activity_Graph.Graphlets._local_codebook` (list)
`Activity_Graph.Graphlets._local_graphlets` (dict)

`utils.graph2dot(Activity_Graph, loc)` now prints the Activity_Graph to a file location.

Please test `./scripts/qstag_example.py` and merge? 
Or let me know if you require any alterations?

### CODE REVIEW

**Comment by marc-hanheide** [comment]
@PDuckworth would you be able to turn the example `./scripts/qstag_example.py` into an actual unit test? @yianni has implemented trillions of tests in https://github.com/strands-project/strands_qsr_lib/tree/master/qsr_lib/tests so there are plenty of examples.

**Comment by marc-hanheide** [comment]
Then, @cdondrup you should know about this ;-)

**Comment by yianni** [comment]
As this is not really ready for merge (spoken with Paul) and will be triggering the unittests on jenkins every time there is a push I will reject the PR.

If someone needs this in alpha state then pull from @PDuckworth branch.

**Comment by marc-hanheide** [comment]
Nothing wrong with unit testing it every time, I'd say. I use open PRs a lot to make sure I make the right changes.

**Comment by yianni** [comment]
Can run them locally without the need to commit and use jenkins.
see [Running unit tests](http://docs.ros.org/indigo/api/catkin/html/howto/format1/run_tests.html)

**Comment by marc-hanheide** [comment]
yes, but then you run them in your own environment, and not a clean fresh installed ubuntu, so you'll miss all the dependency-checks, that account for about 70% of all fails ;-)

**Pull request closed without merging**
