### PR TITLE
Refactored ConDir to car_dir

### PR DESCRIPTION
**Pull request by pet1330**
See #129

### CODE REVIEW

**Comment by yianni** [comment]
Following naming convention can it be refactored to cardir?

**Comment by pet1330** [comment]
Yeah that's fine, I'll do it tomorrow :+1:

**Comment by yianni** [comment]
Yes didn't see you had it updated... I see now the commit... Either assign it to me, or better now we use appropriate tags.

**Comment by yianni** [comment]
Check my pull request on your repo/branch. Got no conflicts when merged master so not sure why it complains here.

If my PR is fine and merged which will auto-update here, change the tag to "ready for review" and assign it to me.

**Comment by pet1330** [comment]
@yianni This needs testing, but should be alright to merge now :)

**Comment by yianni** [comment]
I ll have a look tomorrow, but unit tests should be sufficient for this.

**Comment by yianni** [comment]
Checks pass. Looks alright to me.

**Pull request merged**
