### PR TITLE
closes #30 and #26

### LINKED ISSUE #30: Allow client to optionally request for which objects QSRs will be created
Allow client to optionally request for which objects QSRs will be created. If it is empty then revert to default behavior. Also related to #26

### PR DESCRIPTION
**Pull request by yianni**

### CODE REVIEW

**Comment by marc-hanheide** [comment]
the problem originates from the github DDoS attack...

**Comment by marc-hanheide** [comment]
retest this please

**Comment by yianni** [comment]
@marc-hanheide @cdondrup Failed?

**Comment by marc-hanheide** [comment]
see my comment

**Comment by yianni** [comment]
Just saw it :) What do you mean retest it? Compiles alright on my machine.

**Comment by marc-hanheide** [comment]
That's a "magic phrase" that jenkins understands. It will trigger a new build (as it just did), so it means that jenkins should test it again, not you.

**Comment by yianni** [comment]
OK. Although I just noticed I have a runtime bug (won't break anything though at the moment) so might want to wait 20mins before you merge it to fix it.

**Comment by marc-hanheide** [comment]
sure

**Pull request closed without merging**
