### PR TITLE
QSTAG

### PR DESCRIPTION
**Pull request by PDuckworth**
I've re-tested some simple cases since the documentation was added.

### CODE REVIEW

**Comment by yianni** [comment]
OK, I ll test it when I have time unless anyone else wants to do it.

**Comment by yianni** [comment]
-_-

**Comment by yianni** [comment]
@marc-hanheide this PR requires igraph package. Any chance of getting it installed on Jenkins?

**Comment by yianni** [comment]
This works fine from what I can tell.

But cannot merge until igraph is on jenkins. For 14.04 it is on the repos as `python-igraph` package. @marc-hanheide whenever you have a moment would it be possible to apt-get install this package?

**Comment by cdondrup** [comment]
It has to be a rosdep. You can add it here: https://github.com/strands-project/rosdistro/blob/strands-devel/rosdep/strands.yaml if it is just a debian package. The include it in your package.xml.

**Comment by yianni** [comment]
OK great thanks.

Including in the package.xml with the the build_depend and run_depend will suffice?

**Comment by cdondrup** [comment]
After you added it to https://github.com/strands-project/rosdistro/blob/strands-devel/rosdep/strands.yaml yes.

**Comment by yianni** [comment]
Looking on [this](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_prob_rep/package.xml) you dont have ghmm as build_depend just run_depend. Will give that a shot. Thanks.

**Pull request merged**
