### PR TITLE
extended functionality of add_object_track_from_list to handle 2D and…

### LINKED ISSUE #175: Enhance World_Trace.add_object_track_from_list
Enhance [`World_Trace.add_object_track_from_list`] or better have internal methods that handle lengths 2, 3, 4, 6, but firstly issues #173 and #174 need to be resolved.

### PR DESCRIPTION
**Pull request by yianni**
… 3D points and boxes

closes #175

### CODE REVIEW

**Comment by yianni** [comment]
@PDuckworth test when you can plz. It is as simple as.

```python
world = World_Trace()
o1 = [(numbers), (numbers), (numbers), ...]
world.add_object_track_from_list(o1, "o1")
```

**Comment by PDuckworth** [comment]
I've checked some simple cases. It seems to work fine. 

I will use this function instead of `strands_data_to_qsrlib`, so I can test it with real data then.

```
    #3D points
    o1 = [(1,1,1), (2,2,2), (1,1,1), (2,2,2), (2,2,2), (3,3,3)]
    o2 = [(1,1,1), (2,2,2), (3,4,3), (3,4,3), (3,3,3), (3,3,3)]

    #2D BB
    o1 = [(1,1,5,5), (2,2,5,5), (1,1,5,5), (2,2,5,5), (2,2,5,5), (3,3,5,5)]
    o2 = [(1,1,2,2), (2,2,2,2), (3,4,2,2), (3,4,2,2), (3,3,2,2), (3,3,2,2)]
```

Paul

**Comment by yianni** [comment]
OK thanks. Let me know when you are happy for me to merge. TBH there is no reason to fail if the above tests work.

PS: you can also offset the timestamps by using the argument `t0` ;)

**Comment by PDuckworth** [comment]
I wasn't planning on testing it on real data for a while, so I'm happy for it to be merged. It doesn't look like you broke anything :)

**Pull request merged**
