### PR TITLE
added rcc5 for completeness

### PR DESCRIPTION
**Pull request by yianni**
RCC5 for completeness based on the following figure (Figure 2 in Tony's 2015 survey paper):
screenshot from 2015-09-17 13 20 37

@pet1330 validate that it works correctly please, it should be straightforward :).

Don't worry about jenkins test failing. I will add the unittests after your confirmation.

### CODE REVIEW

**Comment by pet1330** [comment]
I'll try and sort this out on Wednesday.

**Comment by yianni** [comment]
That's fine. Thanks. What worried me is that the HMM tests are also failing so we will need @cdondrup input on this, as I don't know why they do so.

**Comment by cdondrup** [comment]
They passed:

```
[qsr_prob_rep.rosunit-hmm_tester/test_qtcb_sample][passed]
[qsr_prob_rep.rosunit-hmm_tester/test_qtcbc_create][passed]
[qsr_prob_rep.rosunit-hmm_tester/test_qtcbc_loglikelihood][passed]
[qsr_prob_rep.rosunit-hmm_tester/test_qtcbc_sample][passed]
[qsr_prob_rep.rosunit-hmm_tester/test_qtcc_create][passed]
[qsr_prob_rep.rosunit-hmm_tester/test_qtcc_loglikelihood][passed]
[qsr_prob_rep.rosunit-hmm_tester/test_qtcc_sample][passed]
[qsr_prob_rep.rosunit-hmm_tester/test_rcc3_create][passed]
[qsr_prob_rep.rosunit-hmm_tester/test_rcc3_loglikelihood][passed]
[qsr_prob_rep.rosunit-hmm_tester/test_rcc3_sample][passed]
```

**Comment by yianni** [comment]
Not on jenkins, see bottom of [check details page](https://lcas.lincoln.ac.uk/jenkins/job/pr-indigo-strands_qsr_lib/161/). More fail in the PR about RCC4 [see here](https://lcas.lincoln.ac.uk/jenkins/job/pr-indigo-strands_qsr_lib/166/).

**Comment by cdondrup** [comment]
I see.... for some reason it did not start the server in time so the services were not available. I think a wait for service in the ros_client should fix this. Should have done that to begin with... Will open an issue.

**Comment by yianni** [comment]
Nice thanks. Alternatively, they could also be rosunittests which do not depend on the QSRlib ROS service being up, (see here for an example)[https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/tests/mwe_tester.py].

**Comment by yianni** [comment]
PS: But whatever is easier. Egal to me. :)

**Comment by cdondrup** [comment]
But then I wouldn't have found that error ;)

**Comment by pet1330** [comment]
I was meant to report this issue a few days ago, I tried to put my client in a launch file and it kept erroring due to this race condition. I had to call them individually to ensure the server started before client could make it's first request.

**Comment by yianni** [comment]
Or you can write it as unittest which does not require QSRlib ros server and wrap it in a ros unittest. See the other qsr tests other than qtcs.

Yiannis

On 22 Sep 2015, at 14:20, Peter Lightbody <notifications@github.com<mailto:notifications@github.com>> wrote:


I was meant to report this issue a few days ago, I tried to put my client in a launch file and it kept erroring due to this race condition. I had to call them individually to ensure the server started before client could make it's first request.

**Comment by yianni** [comment]
Argh. Nevermind, just saw the conflicts. Will fix them first.

**Comment by pet1330** [comment]
Tested. This is okay to merge. :+1:

**Pull request merged**
