### PR TITLE
adds a number of rostests (unitests) for all QSRs except argprobd and a multiple one

### PR DESCRIPTION
**Pull request by yianni**
Adds rostests for:
* RCC2
* RCC3
* RCC8
* coneDir
* MOS
* MWE
* ArgD

Adds a data file `data1` and a utility to generate ground truth from it.

Missing rostests: argprobd and a multiple.

### CODE REVIEW

**Comment by yianni** [comment]
@cdondrup probably the most appropriate to quickly test this.

**Comment by yianni** [comment]
@marc-hanheide Hmmm, this PR (containing rostests) has not been merged but the rostests have been self-tested neverthless? :O [See here](https://lcas.lincoln.ac.uk/jenkins/job/pr-indigo-strands_qsr_lib/122/testReport/rostest.runner/RosTest/)

Pretty cool if that's the case and I guess it would be safe to merge then without manual testing for someone?

**Comment by marc-hanheide** [comment]
Of course! All ros tests in a PR are run

**Comment by yianni** [comment]
> Of course! All ros tests in a PR are run

Nice!! I guess then no 2nd manual testing needed in this case then.

**Comment by marc-hanheide** [comment]
If your tests have good coverage this will help to assess a PR. Normally it should still be looked at by a colleague. Tests only confirm you didn't destroy something that was working. Not that the PR makes any sense 😉

**Comment by yianni** [comment]
Fair point.

**Comment by cdondrup** [comment]
I won't be able to test this until next week. But I don't think there is any harm in adding tests.

**Comment by yianni** [comment]
I'll interpret that as "merge when you feel ready then" :P.

**Comment by marc-hanheide** [comment]
I couldn't agree more

**Comment by cdondrup** [comment]
Everybody happy then ;)

**Comment by yianni** [comment]
@cdondrup is there a test for argprobd? Example of `qsr_relations_and_values` value?

**Pull request merged**
