### PR TITLE
Rcc2

### PR DESCRIPTION
**Pull request by yianni**
Simplest RCC ever ("dc": disconnect or "c": connect).

Test is quick:
Run the example_ros_client with `rcc2` as argument. The data are in the same if as rcc3.

### CODE REVIEW

**Comment by cdondrup** [comment]
I did the last one @pet1330 this is yours to test ;)

**Comment by yianni** [comment]
Yes thanks. Anyone. I can actually ask @PDuckworth to test this as hopefully doens't break the qsrlib core code.

Unless it is not OK for a different eprson but from the same group to test?

**Comment by pet1330** [comment]
Good news is that it works, bad news is that this, similar to rcc3, can be worked out using rcc8 and filtering the responses. Rather than merging this, it might be better if rcc8 is made into an abstract class and rcc3 and rcc2 inherit from that class with a make file that filters the responses. If everyone thinks this would be a good idea, can do that now?

**Comment by yianni** [comment]
I did it this way cause it was literally a 2min development for that.

Regarding making RCC8 as an abstract class, it might seem a good idea at start and it shouldn't take long to change the RCCs implementations. E.g. RCC2 would make a call to RCC8 abstract and then it's a simple `if relation!=dc: relation=c`, similar ifs for RCC3.

But thinking over it again there is no need to compute something complex only to simplify it later, might as well go to the simple implementation straight away. I.e. keeping them separate in this case is more computationally efficient (ditto only a little bit as they are simple operations, but still).

Other reasons I could think of against this is the dependency on RCC8 abstract class, a bug there would affect all.

From the users point of view either ways would be the same as he would still do the same calls.

That's my thoughts.

**Comment by pet1330** [comment]
The way RCC8 is computed, it works out if the objects are disconnected first, so the remaining states would never be called anyway making it just as fast and error prone. However, if you prefer to keep them separate I would change the logic to the following, as it's only four lines and also faster:

```python
if (bb1[0] > bb2[2]) or (bb1[2] < bb2[0]) or (bb1[1] > bb2[3]) or (bb1[3] < bb2[1]):
            return "dc"
        else:
            return "c"
```

**Comment by yianni** [comment]
@pet1330 Oh well, might as well do it in one line then. :)

**Comment by pet1330** [comment]
Fantastic, that's even better :+1:   I would still consider an abstract RCC class, as I think it will give it more structure without too much detriment.  But for the time being, I've tested it and am happy for it to be merged :smile:

**Comment by yianni** [comment]
@pet1330 Yes maybe. I will commit this since you have tested and are happy and we can see about abstractions at an abstract point in time :).

**Pull request merged**
