### PR TITLE
QTC now returns real qtc symbol strings: +,-,0

### LINKED ISSUE #25: [QTC] QTC returns numpy arrays?
@cdondrup Does the QTC implementation return np.arrays? 

I think @yianni 's idea was that the multiple qsr implementations would return the same type so we can quickly switch between them. RCC3 implementation returns strings.

### PR DESCRIPTION
**Pull request by cdondrup**
Closes #25 and #29 

Requires everything that uses qtc to be changed to use these strings.

### CODE REVIEW

**Comment by cdondrup** [comment]
@PDuckworth I think you might be using qtc for the G4S deployment. Please have a look at the PR in strands_hri linked above on how to convert the strings to numpy arrays if you need that. Otherwise the output is now something like this:
```
Response is:
1: human,robot:-,-; 
2: human,robot:-,0; 
3: human,robot:0,0; 
4: human,robot:0,+; 
5: human,robot:+,+; 
```

**Comment by hawesie** [comment]
Unless this contains bug fixes, I don't think we want to include it in the deployed system, as it goes beyond the code freeze.

**Comment by cdondrup** [comment]
All the PRs I opened are kind of bug fixes because qtc did not behave like the other QSRs. Since I don't want to break a working system, we can of course leave these open or not release them but I would leave the decision if we want to merge this befor the deployment to @PDuckworth @yianni and @jayyoung since they are using the library, if you don't object @hawesie.

**Comment by PDuckworth** [comment]
I have been testing all my code using the distance based QSRs `arg_distance` in qsrlib. 

I think it will be easy to use the new QTC relations on the obtained dataset for offline analysis of techniques etc. Especially if @hawesie doesn't want to include them in the deployed system. I'm easy though.

**Comment by yianni** [comment]
Yes QTC behaved differently than the others so it did create confusion initially or to someone firstly using QSRlib and QTC. Regarding the code freeze I leave this decision to @PDuckworth.

@cdondrup Keeping QSRs as strings was a decision at time as the first QSR did not hold multiple relations. Of course it is trivial to make them an iterable by `s.split(",")` but that requires an extra step and creates confusion IMO. I am open to discuss changing the API to have the `.qsr` member as an iterable instead of the current string. But this is something that although probably should not go in the deployment it should be done fairly soon before more QSRs are included. Open a separate ticket for this where we can discuss it?

**Comment by hawesie** [comment]
Ok, I also leave this to the mighty @PDuckworth

**Comment by PDuckworth** [comment]
Whhaaat?! :) 
I don't really have time to test i these updates properly before Monday. I also don't really need qtc for the deployment, as I switched to using arg_distance a while ago and they seem to work fine. So for ease, I wouldn't put it in the deployed system. But I would very much like to use them after the deployment on the data we generate.

**Comment by cdondrup** [comment]
As I said, we can leave this open for now. I understand that everything is a bit busy now and you don't have time to test it. If you do after the start of the deployment, it'd be nice if you could give it a quick try. The strings itself work, the only thing is that I don't know if it breaks anything using QTC.

**Comment by cdondrup** [comment]
Just pinging again to see if we can merge this. No one seems to use it currently anyway.

**Comment by hawesie** [comment]
If @PDuckworth  says so I'll click the button.

**Comment by cdondrup** [comment]
@PDuckworth any thoughts? This open for quite a while now already and so are #38 #39 
Judging from your previous statement: "I also don't really need qtc for the deployment, as I switched to using arg_distance a while ago..." I guess this should be fine to merge?! Please reply.

**Comment by PDuckworth** [comment]
Hi @cdondrup, I am planning to test this (along with checking the trajectories obtained in the g4s deployment) sometime this week. 
Sorry it's been so delayed.

**Comment by PDuckworth** [comment]
@cdondrup @hawesie I have tested this with my episode service, and two objects (the trajectory and one static soma object), and it's fine.  

I also need #38 accepting for it to be useful (to analyze the g4s data).

**Comment by yianni** [comment]
@cdondrup @hawesie 
OK since @PDuckworth has tested and is happy and these are independent in terms of in-between issues I will merge it.

**Pull request merged**
