### PR TITLE
fixed doc for rtd

### PR DESCRIPTION
**Pull request by yianni**

### CODE REVIEW

**Comment by yianni** [comment]
just docs meddling

**Comment by pet1330** [comment]
Why did you merge this before accepting the condir pull request?

**Comment by yianni** [comment]
Didn't see if the condir was updated. I thought it wasn't done. Sorry, I can resolve the conflicts.

Hence, the "in-progress" and "ready for review" tags.

**Comment by pet1330** [comment]
That's ok, I don't have permissions to change tags anyway.

**Comment by yianni** [comment]
Just leave a note that it is ready for review then and I can change the tag.

**Pull request merged**
