### PR TITLE
Trace from list

### PR DESCRIPTION
**Pull request by yianni**
Takes a list of lists/tuples representing the trace of an object and adds them in a world_trace.

Simple to debug, add the following in the end of [`world_trace.py`](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/src/qsrlib_io/world_trace.py) and then just run the file.
```python
if __name__ == '__main__':
    world_trace = World_Trace()
    w = 1
    l = 1
    o1 = [(1,1,w,l), (2,1,w,l), (3,1,w,l)]
    o2 = [(1,1,w,l), (1,2,w,l), (1,3,w,l)]
    o3 = [(0,0), (0,0)]

    world_trace.add_object_track_from_list(obj_name="a", track=o1)
    world_trace.add_object_track_from_list(obj_name="b", track=o2)
    world_trace.add_object_track_from_list(obj_name="c", track=o3, t0=2)

    for t in world_trace.get_sorted_timestamps():
        print("---\n%d" %t)
        print(world_trace.trace[t].objects.keys())
        for k, v in world_trace.trace[t].objects.items():
            print(k, (v.x, v.y, v.width, v.length))
        print()
```

### CODE REVIEW

**Comment by cdondrup** [comment]
How would this work with custom kwargs parameters?

**Comment by yianni** [comment]
I assume you mean the kwargs in the Object_State. It won't, it's only to fill in coordinates as often trajectories are given as csv values, so after reading them and possibly changing the list of tuples to (x,y,w,l) then you can add them easily.

If kwargs are needed maybe if that's OK with you merge if it works and file an enhancement issue and I can think about how to do this also. But this particular method is really meant for simple csv points/regions adding.

**Comment by cdondrup** [comment]
I just fear that someone might try to use it with qtc (or any other relation where you need more than x,y,w,l) and it will fail for no obvious reason.

**Comment by cdondrup** [comment]
Your test works for me. I know that [parsing is a pain](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/scripts/example_ros_client.py#L162-L183) but I still think this is somewhat risky.

**Comment by yianni** [comment]
Agree, but wouldn't qtc throw an exception or something then?

And for this to work there should be some header file on top... also risky as the header must contain the same names of the kwargs....

An alternative is to optionally provide the name of the qsr in the first line and have a mask built-in for it?

By the way do the kwargs change for each object and over time in qtc?

**Comment by cdondrup** [comment]
They don't change over time, no, and qtc will throw an exception, true. See #53 which would take care of most of the kwargs for the object. One of them might remain on object level but only for qtcbc which I don't think anyone but me is using. Therefore no great harm done. In general there might be other qsrs that will need object specific kwargs.

Wouldn't a solution be to add kwargs to `add_object_track_from_list` and append them when creating the object? I could then just call:

```
world_trace.add_object_track_from_list(obj_name="a", track=o1, spam="eggs")
```

I admit that this is not nice because you have to know what you are doing but it would at least allow to add them.

**Comment by yianni** [comment]
OK, done. Retest when you can please.

**Comment by yianni** [comment]
@cdondrup ok to merge?

**Comment by cdondrup** [comment]
Will test this next week. Sorry for the long delay.

**Comment by yianni** [comment]
No worries. If you could also look into #53 when you have time (IMO easiest and best way to do it is by using `dynamic_args` in the request message, see [here](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/scripts/example_ros_client.py#L295) and [here](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/src/qsrlib_qsrs/qsr_arg_relations_distance.py#L83))

**Comment by cdondrup** [comment]
Seems to work

**Comment by yianni** [comment]
Thanks for testing the recent PRs.

**Pull request merged**
